vim/merlin/autoload/merlin.py

Fix vim encoding

---

vim/merlin/syntax/merlin.vim

Update .merlin syntax highlighting for vim

---

vim/merlin/autoload/merlin.vim
vim/merlin/doc/merlin.txt

I'd like to address #381 and provide a way to disable default keybindings for vim.
Thanks!

vim: provide mechanism to disable the default keybindings.

---

emacs/merlin.el

as discussed in issue #294.
I'm using it and find it quite convenient.

set the emacs mark on merlin--goto-file-and-point

---

src/kernel/mppx.ml

Some ppx ([ppx_implicits](https://bitbucket.org/camlspotter/ppx_implicits), for example) uses include paths to refer to other files. The paths are propagated from `ocamlc`/`ocamlopt`'s `-I` parameter to the ppxs. However, current merlin seems not to simulate it well.
This fix will set `Clflags.include_dirs` before calling ppxs (and restores them after call). 
In `Pparse.apply_rewriters`, [`Ast_mapper.add_ppx_context_str` is called](https://github.com/ocaml/merlin/blob/d27a113ad6a103f2679c81706eb2427e74ac8882/src/ocaml/support/pparse.ml#L94) to append a `[@@ocaml.ppx.context]` attribute which includes that paths.

Pass include paths to ppx

---

src/ocaml/typer_403/typing/short_paths_graph.mli
src/ocaml/typer_405/typing/env.ml
src/ocaml/typer_405/typing/env.mli
src/ocaml/typer_405/typing/predef.mli
src/ocaml/typer_405/typing/printtyp.ml
src/ocaml/typer_405/typing/short_paths.ml
src/ocaml/typer_405/typing/short_paths.mli
src/ocaml/typer_405/typing/short_paths_graph.ml
src/ocaml/typer_405/typing/short_paths_graph.mli
src/ocaml/typer_405/typing/typeclass.ml
src/ocaml/typer_405/typing/typedecl.ml
src/ocaml/typer_405/typing/typemod.ml
src/ocaml/typer_405/typing/typemod.mli

This adds the new short paths implementation for OCaml version 4.05.

Add 4.05 short paths

---

emacs/merlin.el
src/utils/sexp.ml

Fixes https://github.com/ocaml/merlin/issues/710

Emacs: Interpret the "value" returned by Merlin as multibyte

---

src/ocaml/typer_403/typing/short_paths.ml
src/ocaml/typer_404/typing/short_paths.ml
src/ocaml/typer_405/typing/short_paths.ml

This adds protection from recursive module aliases to the short paths implementation. Should fix #759.

Protect against recursive aliases in short paths

---

emacs/merlin.el

Little things that I had lying around.

Trivial simplifications

---

Makefile
emacs/merlin-xref.el
emacs/merlin.el
merlin.install

Merlin xref

---

.travis.yml
merlin.opam
tests/completion/jbuild
tests/config/flags/jbuild
tests/config/jbuild
tests/destruct/jbuild
tests/locate/ambiguity/jbuild
tests/locate/context-detection/jbuild
tests/locate/functors/jbuild
tests/locate/issue802/jbuild
tests/locate/local-definitions/jbuild
tests/locate/non-local/jbuild
tests/locate/partial-cmt/jbuild
tests/locate/reconstruct-identifier/jbuild
tests/locate/sig-substs/jbuild
tests/motion/jbuild
tests/no-escape/jbuild
tests/recovery/jbuild
tests/type-expr/jbuild

ocaml-cram 1.0.0 has been released and has been renamed craml

Rename ocaml-cram to craml

---

merlin.opam
src/utils/dune

and add appropriate opam constraints
Signed-off-by: Rudi Grinberg <rudi.grinberg@gmail.com>

Fix build against latest sturgeon

---

src/analysis/typedtrie.ml
tests/locate/functors/included.t
tests/locate/functors/nested_applications.t

Fixes broken test: `tests/locate/functors/included.t`.

Locate through included functor application

---

src/ocaml/typing/403/btype.ml
src/ocaml/typing/403/btype.mli
src/ocaml/typing/403/env.ml
src/ocaml/typing/403/typeclass.ml
src/ocaml/typing/404/btype.ml
src/ocaml/typing/404/btype.mli
src/ocaml/typing/404/env.ml
src/ocaml/typing/404/typeclass.ml
src/ocaml/typing/405/btype.ml
src/ocaml/typing/405/btype.mli
src/ocaml/typing/405/env.ml
src/ocaml/typing/405/typeclass.ml
src/ocaml/typing/406/btype.ml
src/ocaml/typing/406/btype.mli
src/ocaml/typing/406/env.ml
src/ocaml/typing/406/typeclass.ml
src/ocaml/typing/407/btype.ml
src/ocaml/typing/407/btype.mli
src/ocaml/typing/407/env.ml
src/ocaml/typing/407/typeclass.ml
src/ocaml/typing/407_0/btype.ml
src/ocaml/typing/407_0/btype.mli
src/ocaml/typing/407_0/env.ml
src/ocaml/typing/407_0/typeclass.ml
tests/short-paths/dune
tests/short-paths/test.ml
tests/short-paths/test.t

Don't add dummy class definitions to the short paths graph

Fix #907 and #843

---

src/frontend/lsp/ocamlmerlin_lsp.ml
src/lsp/protocol.ml

- remove some tabs used instead of spaces
- fix a conversion between type and json value
- add missing field in a type
- small additions to completion

Lsp misc cleanup

---

src/frontend/lsp/ocamlmerlin_lsp.ml
src/lsp/protocol.ml
src/lsp/rpc.ml
src/lsp/rpc.mli
tests-lsp/__tests__/textDocument-codeLens.test.ts

This reuses merlin's outline feature and returns types per position.
TODO:

LSP: Implement textDocument/codeLens

---

src/frontend/lsp/ocamlmerlin_lsp.ml
src/lsp/protocol.ml
src/lsp/rpc.ml
src/lsp/rpc.mli
tests-lsp/__tests__/textDocument-documentHighlight.test.ts

https://microsoft.github.io/language-server-protocol/specification#textDocument_documentHighlight

LSP: add document highlight support

---

.travis.yml
merlin.opam

travis: use released version of mdx

---

emacs/merlin.el

Refactor `merlin--point-of-pos` to be a pure function that can return
positions outside of the narrowed region. `merlin--goto-char` now uses
`merlin--point-of-pos` and widens if necessary.
Update callers to use `merlin--point-of-pos` if they don't want widening.
Also simplify `merlin--search`, which never used its second argument.
Fixes #886.

Emacs: Ensure we handle buffer narrowing correctly

---

src/frontend/lsp/ocamlmerlin_lsp.ml
tests-lsp/__tests__/textDocument-completion.test.ts
tests-lsp/__tests__/textDocument-hover.test.ts

LSP positions are starting from line 0 column 0. Merlin positions are
starting from line 1 column 0.

LSP: fix conversion from LSP position to merlin position

---

src/ocaml/preprocess/lexer_ident.mll
tests/locate/reconstruct-identifier/dune
tests/locate/reconstruct-identifier/escaped_newline.ml
tests/locate/reconstruct-identifier/newline_in_quotes.ml
tests/locate/reconstruct-identifier/newlines.t

Do not ignore new lines in Lexer_ident

---

vim/merlin/dune

This file has been in the source tree for a little while now but it was not being installed.

Install vim/ftplugin/reason.vim

---

src/frontend/lsp/dune

This makes it compile with 4.02.3

ocamlmerlin-lsp: depend on result

---

src/frontend/ocamlmerlin/query_json.ml
vim/merlin/autoload/merlin.py

Fixes https://github.com/ocaml/merlin/issues/978

vim: Display warn-error warnings as errors

---

merlin-lsp.opam

* Add dependency on merlin
* Dune isn't a just build dependency

Merlin lsp opam file changes

---

tests/dune.inc
tests/gen/gen_tests.ml

allows us to run tests individually

generate an alias per test

---

tests/test-dirs/destruct/basic.t

Invalid destruct calls aren't handled properly.

Add failing test for destruct

---

src/ocaml/typing/408/typemod.ml
src/ocaml/typing/409/typemod.ml
tests/test-dirs/no-escape/test.t

Catch (and try to report) environment initialization errors.

---

src/frontend/query_commands.ml

So this is why it wasn't working in my tests

Add -kind support to complete-prefix

---

src/analysis/expansion.mli

Add expansion.mli

---

tests/dune.inc
tests/test-dirs/completion/application_context.ml
tests/test-dirs/completion/application_context.t

Add tests for the application context

Improve completion tests

---

src/analysis/type_enclosing.mli

Add an mli with some doc for type-enclosing

---

CHANGES.md

We are about to release 3.3.4 version.
I will submit the release once this PR is approved.

Prepare 3.3.4 release

---

src/analysis/outline.ml
src/frontend/ocamlmerlin/query_json.ml
src/frontend/query_protocol.ml
tests/test-dirs/outline/run.t

This will be renedered in the LSP outline

Add deprecation flag to outline items

---

CHANGES.md

We are about to release 3.3.5 version.
I will submit the release once this PR is approved.

Add merlin 3.3.5 changelog

---

dot-merlin-reader.opam
merlin.opam
src/dot-merlin/dot-protocol/dune
src/utils/dune
src/utils/std.ml

This restore compatibility with the newest `csexp` release.

Restore compatibility with `csexp` 1.2.3

---

.github/workflows/main.yml
main.yml

Once the OCaml installation cached the CI should be faster than travis.

[Experiment] Add Github Actions workflow

---

.github/workflows/main.yml
.travis.yml
merlin.opam
tests/merlin-wrapper-template

This is a follow-up of https://github.com/ocaml/merlin/pull/1167#issuecomment-686876059. I tested this on MacOS using Travis with this PR + https://github.com/ocaml/merlin/pull/1167 (see full logs: https://travis-ci.org/github/ocaml/opam-repository/jobs/724010830) and it works.
@rgrinberg what was the issue you were hitting in https://github.com/ocaml/merlin/pull/1041?

Enable tests on MacOS

---

src/dot-merlin/dot_merlin_reader.ml

Fix issue 1179

---

tests/dune.inc
tests/test-dirs/type-enclosing/types/alias.t

Check that Merlin is not the cause of ocaml/ocaml-lsp#303

Add test for type alias

---

src/analysis/dune
src/dot-merlin/dot-protocol/dot_protocol.ml
src/dot-merlin/dot-protocol/dot_protocol.mli
src/dot-merlin/dot_merlin_reader.ml
src/frontend/dune
src/frontend/ocamlmerlin/dune
src/kernel/dune
src/ocaml/merlin_specific/dune
src/ocaml/parsing/dune
src/ocaml/preprocess/dune
src/ocaml/typing/dune
src/ocaml/utils/dune
src/utils/dune
tests/gen/gen_tests.ml

It contains some commonly named modules that are best prefixed.

Wrap merlin_utils

---

src/analysis/dune
src/frontend/dune
src/frontend/ocamlmerlin/dune

Perhaps the name could be changed to something more friendly, but this is enough
to solve my immediate problem.

Wrap merlin_analysis

---

dune-project
merlin.opam

~WIP~, just in case you wanna keep this CI

Fix failures in OCaml-CI

---

README.md
emacs/merlin.el
merlin.opam

They are compatible 2.0 & 2.1+
cf. ocaml/opam#4503

Use opam var instead of opam config var

---

dot-merlin-reader.opam

Mirrors https://github.com/ocaml/opam-repository/pull/18164/commits/6bd16abc7008bd8a4b7e486ef16143e74d0a787a

dot-merlin-reader.opam: Fix dune constraint

---

.github/workflows/main.yml
dot-merlin-reader.opam
tests/dune.inc
tests/gen/gen_tests.ml
tests/test-dirs/config/dot-merlin-reader/quoting/quoting.t
tests/test-dirs/destruct/complete.t
tests/test-dirs/destruct/create.t
tests/test-dirs/destruct/refine.t
tests/test-dirs/file-cache/test.t
tests/test-dirs/typer-cache/test.t
tests/test-dirs/warnings/backtrack.t

This PR:
- Makes Github Actions test Merlin in release mode (thus we have both release and non-release mode tests)
- Fix OCamlCI massively parallel tests by 
- using distinct material for each test 
- adding locks to the merlin-server tests
Sadly an issue persists with 4.02: OCamlCI ignore the fact that tests are deactivated and fails.

[3.4][CI] Improve the CI

---

README.md
emacs/merlin-ac.el
emacs/merlin-company.el
emacs/merlin-iedit.el

Follow-up to https://github.com/ocaml/merlin/pull/1247

Update Emacs usage docs where applicable

---

.gitignore
README.md
emacs/merlin-ac.el
emacs/merlin-cap.el
emacs/merlin-company.el
emacs/merlin-iedit.el
emacs/merlin-imenu.el
emacs/merlin-xref.el
emacs/merlin.el
merlin.opam
src/analysis/destruct.new.ml
src/analysis/destruct.old.ml
src/frontend/query_commands.ml
src/kernel/mppx.ml
src/ocaml/driver/pparse.ml
src/platform/platform_misc.c
tests/dune.inc
tests/test-dirs/config/workdir.t/dune-project
tests/test-dirs/destruct/errors.t
tests/test-dirs/destruct/issue1300_since_408.t
vim/merlin/autoload/merlin.py
vim/merlin/autoload/merlin.vim

Backports to 3.4

---

dot-merlin-reader.opam
merlin.opam

See discussion in https://github.com/ocaml/opam-repository/pull/18494

[opam] Apply changes suggested by @mseri

---

tests/test-dirs/refactor-open/record_field.t

refactor-open record field bug test

---

CHANGES.md
src/analysis/type_enclosing.ml
tests/test-dirs/type-enclosing/objects.t/run.t
tests/test-dirs/type-enclosing/objects.t/test.ml

Fix type enclosing on methods

---

CHANGES.md
src/analysis/namespaced_path.ml
src/analysis/typedtrie.ml
tests/test-dirs/locate/issue1199.t

Not confident this is correct, but it should be easy to evaluate since it's a tiny patch.

Attempt to fix #1199

---

src/ocaml/typing/typecore.ml
tests/test-dirs/type-enclosing/issueLSP444.t

pattern recovery: only in normal mode

---

.github/workflows/emacs-lint.yml
emacs/check.sh
emacs/merlin-ac.el
emacs/merlin-cap.el
emacs/merlin-company.el
emacs/merlin-iedit.el
emacs/merlin-xref.el
emacs/merlin.el

@jamesjer : I was not able to push to your branch so I opened a new PR with your changes plus a few others. Thanks again for your fix !

[emacs] Fix `merlin-locate` calls and replace `first/rest` by `car/cdr` in holes commands

---

src/analysis/construct.ml
src/ocaml/parsing/pprintast.ml
tests/test-dirs/construct/c-simple.t

Building a curried function doesn't count as going deeper.

[Construct] eagerly build functions

---

src/analysis/browse_tree.ml
src/analysis/browse_tree.mli
src/analysis/refactor_open.ml
src/ocaml/merlin_specific/browse_raw.ml
src/ocaml/merlin_specific/browse_raw.mli
tests/test-dirs/refactor-open/functor-app.t/run.t
tests/test-dirs/refactor-open/functor-app.t/test.ml
tests/test-dirs/refactor-open/record_field.t
tests/test-dirs/refactor-open/unqualify.t

Refactor open fixes

---

.gitattributes
.github/workflows/main.yml
tests/test-dirs/dune
tests/test-dirs/locate/with-holes.t/run.t

New attemps at enabling windows CI.

Windows ci

---

src/analysis/destruct.ml
tests/test-dirs/destruct/record.t

Record field projections were a bit broken, so adding a bunch of tests, and some fixes.

Destruct record field

---

src/kernel/mconfig.ml

Ignore `-error-style` compiler flag

---

CHANGES.md
src/kernel/mconfig.ml
src/ocaml/utils/warnings.ml
tests/test-dirs/alerts.t/run.t

Add support for `-alert` compiler flag

---

src/kernel/mppx.ml
src/ocaml/driver/pparse.ml
src/platform/platform_misc.c

Fixes #1420 
This is a cherry-pick from @rgrinberg's fork of Merlin for LSP.
@MisterDA could you test that this patch works well on Windows ? You need a project with a ppx.

Stop using chdir for ppx

---

CHANGES.md
src/frontend/ocamlmerlin/ocamlmerlin_server.ml
src/kernel/mconfig_dot.ml
src/ocaml/typing/magic_numbers.ml
src/utils/lib_config.ml
src/utils/lib_config.mli

Allow customization of error messages

---

Makefile
bench.Dockerfile
tests/test-dirs/locate/issue1424.t

test: locate work as expected when the cmt are built

---

README.md

As suggested by @voodoos in #1604

Add readme note about menhir pin

---

CHANGES.md
src/analysis/construct.ml
tests/test-dirs/construct/c-depth.t
tests/test-dirs/construct/c-objects.t
tests/test-dirs/construct/c-parenthesis.t
tests/test-dirs/construct/c-prefix.t
tests/test-dirs/construct/c-simple.t

Fix `construct` results ordering for sum types and poly variants

---

CHANGES.md
src/ocaml/typing/typecore.ml
tests/test-dirs/completion/dune
tests/test-dirs/completion/issue1575.t

Fix object method completion

---

CHANGES.md
src/analysis/context.ml
tests/test-dirs/type-enclosing/issue1607.t

Improve context detection for package types

---

CHANGES.md
src/ocaml/preprocess/lexer_raw.mll
tests/test-dirs/string-loc.t

Fix location of string constants

---

CHANGES.md
src/analysis/browse_tree.ml
src/analysis/browse_tree.mli
src/ocaml/merlin_specific/browse_raw.ml
src/ocaml/merlin_specific/browse_raw.mli
tests/test-dirs/occurrences/ext-variant.t

Fixes https://github.com/ocamllabs/vscode-ocaml-platform/issues/1185

Fix occurrences of extension constructors

---

CHANGES.md
src/ocaml/driver/pparse.ml

ppx: fix debug printing crashing on windows

---

.github/workflows/emacs-lint.yml
CHANGES.md
emacs/merlin.el

(following the discussion in https://github.com/ocaml/merlin/issues/1386)
Cc @monnier @voodoos FYI
For a quick recap of the changes and their motivation, see also the table from comment:
https://github.com/ocaml/merlin/issues/1386#issuecomment-1701567716
Close #1386

fix(merlin.el): Fix and improve emacs bindings

---

editor/emacs/index.markdown

docs: Update online documentation w.r.t. PR #1668

---

CHANGES.md
src/analysis/locate.ml

Prevent looping in scrape-aliases (fixes ocaml/ocaml-lsp#1192)

---

CHANGES.md
doc/dev/CACHING.md
emacs/merlin.el
src/frontend/ocamlmerlin/new/new_merlin.ml
src/kernel/mconfig.ml
src/kernel/mconfig.mli
tests/test-dirs/config/dot-merlin-reader/quoting.t
tests/test-dirs/server-tests/cache-time.t

This PR changes cache flag to a more descriptive name

Change flag name from `-cache-period` to `-cache-lifespan`

---

.github/workflows/main.yml
CHANGES.md
doc/dev/CACHING.md
emacs/merlin.el
src/analysis/locate.ml
src/frontend/ocamlmerlin/new/new_merlin.ml
src/frontend/ocamlmerlin/ocamlmerlin_server.ml
src/kernel/mbrowse.ml
src/kernel/mconfig.ml
src/kernel/mconfig.mli
src/ocaml/preprocess/dune
src/ocaml/typing/typedecl.ml
src/ocaml/typing/typetexp.ml
tests/test-dirs/config/dot-merlin-reader/quoting.t
tests/test-dirs/document/issue1513.t
tests/test-dirs/errors/issue1704-wrong-message.t
tests/test-dirs/locate/local-build-scheme.t
tests/test-dirs/locate/non-local/ignore-kept-locs.t/run.t
tests/test-dirs/server-tests/cache-time.t
vim/merlin/autoload/merlin.vim

- #1701 from voodoos/501-backports
- #1715 from voodoos/501-backports

Backports for release 4.13-500

---

.github/fuzzy-ci-helpers/irmin.3.9.0.opam.locked
.github/fuzzy-ci-helpers/label_name.txt
.github/fuzzy-ci-helpers/msg.txt
.github/workflows/fuzzy-ci-privileged.yml

This PR lies the ground for [the PR that introduces a Fuzzy CI for `ocamlmerlin`](https://github.com/ocaml/merlin/pull/1716).
The Fuzzy CI is triggered by a PR. It expects to find two things on that PR's target branch:
- A lock file for Irmin.
- A workflow that executes one of two kinds of instructions: Comment on the PR or delete a label on the PR. These two kinds of instructions need to live in a separate workflow from the rest of the Fuzzy CI for security reasons: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
Those two things are what this PR adds. Once we've merged this PR, the PR that introduces the Fuzzy CI can itself serve as a test for the Fuzzy CI mechanism.

Lie the ground for the Fuzzy CI

---

src/ocaml/preprocess/recover/gen_recover.ml
src/ocaml/preprocess/recover/synthesis.ml

Ignore new Menhir deprecations

---

CHANGES.md
src/analysis/destruct.ml

A follow up of #1800, based on https://github.com/ocaml/merlin/pull/1800#issuecomment-2253532309

Check always that default args are option

---

CHANGES.md
vim/merlin/autoload/merlin.py

I back ported the changes from issue #1798 since I ran into them recently.

Backport changes from issue #1798

---

doc/dev/PROTOCOL.md

Fix #1835 
cc @voodoos should maybe included in the backport pre-release?

Document missing commands in PROTOCOL.md

---

merlin-lib.opam
merlin.opam
ocaml-index.opam

Add maintenance intent to opam files

---

Makefile
bench.Dockerfile

Add a hughe buffer in the performance process (I think we need to merge it in order to trigger the Bench CI?)

Add `big-bertha` in merl-an bench

---

.github/workflows/ocaml-lsp-compat.yml
CHANGES.md

Bump version in LSP compat check and update readme

Prepare for release 5.6-503
