ocaml/merlin

- emacs/merlin.el
Some of the arguments that are sent to merlin process, in particular
buffer-file-name, might contain text properties. This changes how they
are printed and that causes merlin process to choke on them which in
turn creates bunch of "spurious communication" errors in emacs. Just
dropping text properties fixes the issues.
> Drop text properties from command sent to merlin process.

- .gitattributes
- .gitignore
- Makefile
- configure
- vim/merlin/autoload/merlin.py
Finally found some time for upgrading Merlin from the patched 1.6 I'd been using. Patches very similar to those for #194 (some issues had already been fixed or become irrelevant) only as I'm a bit less unfamiliar with git now, I've broken the changes into multiple commits for easier cherry picking if necessary.
An adapted version of this branch also compiles against v2.2 (the whitespace clean-up of vim/merlin/autoload/merlin.py in 8c28e236 means the patch doesn't apply cleaning against v2.2)
I've tested it with gVim 7.4.752 x64 on Windows 7 with Python 2.7.10/3.4.3 for OCaml 4.02.2 i686-w64-mingw32 and it seems to be working beautifully.
a3b240b is critical for building with native Windows ports as ln isn't available
acc4ceb is critical for Vim support on Windows - since reporting that in …
> Revised commits for Windows/mingw32

- emacs/merlin-compat.el
Hi:
I've added a compatibility alias for `merlin-send-command-async` which was renamed in 4817aa94fec4abdbbd06f5c57c117078a2e0eaf4, and this function is currently used in `flycheck-ocaml.el`
> Add alias for `merlin-send-command-async`

- vim/merlin/doc/merlin.txt
Some commands (e.g. `MerlinLocate`) had unprefixed names mentioned as
aliases. That's incorrect and breaks :help (e.g. :h Locate)
> Remove unprefixed versions of command from help

- Makefile.ocamlmakefile
- emacs/merlin.el
- src/analysis/jump.ml
- src/analysis/jump.mli
- src/frontend/IO.ml
- src/frontend/command.ml
- src/frontend/protocol.mli
- vim/merlin/autoload/merlin.py
- vim/merlin/autoload/merlin.vim
This pull request implements a jump command that lets you quickly move to the logical parent nodes in your code.  It is very useful to quickly check the function you're in or even more useful to check the module you're in. One can also jump to let binding and match statement.
It is somehow related to #414.
I'm pretty sure that using `<localleader>j` in vim is a bad idea but I left it for testing. I'll wait for your suggestion.
I imagine people may want different keybinding for different sub commands. Because you can do `:MerlinJump target` where target is a subset of `fun,let,module,match`. For example @bmillwood was interested in just using `:MerlinJump module` and not really `:MerlinJump fun`. So we should make it easy to customize (or maybe just more detailed documentation would be …
> Add jump command

- emacs/merlin.el
> Enable merlin in virtual Emacs buffers

- emacs/merlin.el
`merlin-flags-set` is defined two times.
> Remove duplicated function

- emacs/merlin.el
I changed the separator from comma to space but forgot to change that in `emacs.el`
> Fix keywords separator in emacs

- vim/merlin/doc/merlin.txt
Caused by the addition of the `Merlin` prefix
> Fix vim doc typos

- src/analysis/track_definition.ml
- src/kernel/dot_merlin.ml
- src/kernel/dot_merlin.mli
- src/kernel/merlin_lib.ml
- vim/merlin/syntax/merlin.vim
Summary: In the `ocamlc`/`ocamlopt` compiler, there is no restriction on
which file suffixes may be used. To use a file with a non-standard
suffix, you would supply the file as either `-intf` or `-impl` (note,
you would also tell the compiler that a `-impl` file has a corresponding
interface in a particular suffix by specifying `-intf-suffix`). However,
until this diff, merlin only searches for files with the `.ml/.mli`
suffixes. This diff adds support for checking other suffixes when
locating files. Merlin's heuristic will sometimes try appending `.ml` to
the end of a module name, etc - this diff allows you to instruct it to
also try other suffixes. It works great!
Test Plan:
Reviewers:
CC:
> [Merlin] Add support for SUFFIX flags.

- vim/merlin/autoload/merlin.py
- vim/merlin/autoload/merlin.vim
Allows specifying of merlin binary flags via a global config in Vim.
@yunxing
> Add ability to supply custom flags to merlin binary from Vim

- doc/dev/ARCHITECTURE.md
Now there is a line break between each item instead of them all being on the same line.
> Fixed newlines in architecture documentation

- src/kernel/dot_merlin.ml
- src/kernel/dot_merlin.mli
Adding a new directive "SEARCH" to .merlin that sets the findlib search path for the project, overriding any OCAMLPATH variable
> findlib search path

- vim/merlin/doc/merlin.txt
The link in the VIM documentation which demonstrates the MerlinDestruct function is broken.
> Fixed broken link to MerlinDestruct video

- emacs/merlin-iedit.el
This works even if the user is [autoloading](https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html) iedit; the current version fails with "Symbol's value as variable is void".
> Make merlin-iedit-occurrences even more friendly

- vim/merlin/autoload/neomake/ocaml.vim
Modeled after the Syntastic formatter, the Merlin Neomake maker can be
enabled by setting `let g:neomake_ocaml_enabled_makers = ['merlin']`.
I can also update the vim from scratch wiki if this is merged.
> Add Neomake Maker

- vim/merlin/autoload/merlin.vim
Hey guys! First of all thanks for Merlin. The badassery it brings to writing Ocaml in vim is unrivalled.
From a fresh start on macOS 10.12.5, with vim 8.0.1666, I got this from the get go:
```
Error detected while processing function merlin#Register[117]..merlin#LoadProject:
line    2:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/ostera/.opam/system/share/merlin/vim/autoload/merlin.py", line 740, in setup_merlin
failures = command("project","get")
File "/Users/ostera/.opam/system/share/merlin/vim/autoload/merlin.py", line 201, in command
return merlin_process().command(context(cmd))
File "/Users/ostera/.opam/system/share/merlin/vim/autoload/merlin.py", line 175, in merlin_process
instance = vim.eval("merlin#SelectBinary()")
vim.error: Vim(let):E716: …
```
> [Fix] Check that merlin_home is present in autoload/merlin.vim

- vim/merlin/autoload/merlin_type.vim
Solves #662 
it looks like neovim has a different indexing than vim, that causes
vim.buffers[idx] to throw a `list index out of range` error.
the code in this pr will make it work on both vim and neovim by building
a list of buffers that match the id, rather than assuming that the
buffer id matches the bufferlist id.
> Fix #662 - TypeOf error with neovim

- vim/merlin/doc/merlin.txt
I often find myself looking for this information, and Deoplete has a different regex syntax, which means you can't just reuse neocomplcache's example. Also, Deoplete and Neocomplete are the current completion engines for Neovim and Vim, respectively.
> Vim: add info to help file about using Neocomplete and Deoplete

- vim/merlin/autoload/merlin.py
- vim/merlin/autoload/merlin.vim
- vim/merlin/autoload/merlin_type.vim
Internal buffer names are wrapped with asterisks which causes problems on Vim for Windows since it causes the filename globber to be invoked. Using colons works (and also has the benefit of creating an illegal filename, rather than one which is simply unlikely).
Without this change, the call to `bot split *merlin-type-history*` in `merlin_type.vim` causes an error message and the user's buffer gets the type information instead.
> Use colons rather than asterisks for Vim names

- configure
The Cygwin packages for awk, grep and sed were updated on 20 February 2017 so that they no longer automatically strip `\r` characters on binary mounts. Add `tr` calls in various places in configure to get rid of them.
This also fixes the findlib version test, which would never have worked.
References:
* https://cygwin.com/ml/cygwin/2017-02/msg00152.html
* https://cygwin.com/ml/cygwin/2017-02/msg00189.html
* https://cygwin.com/ml/cygwin/2017-02/msg00188.html
> Fix `\r` problems on recent Cygwins

- src/platform/os_ipc_stub.c
For clang one needs to include the alloca.h header file to make alloca available.
> Added missing include of alloca.h.

- src/frontend/ocamlmerlin.c
- src/platform/os_ipc_stub.c
This gets merlin to compile on FreeBSD.  I don't think it's probably the most portable solution (other BSD's might need to be covered).
> FIX Support compiling on FreeBSD

- vim/merlin/autoload/merlin.py
> Preserve newlines in documentation for display in vim's scratch view

- emacs/merlin.el
This fixes the malformed header in `merlin.el`, which has been preventing `package.el` (and therefore MELPA) from reading package metadata from the file.
> Fix emacs package header formatting

- vim/merlin/autoload/merlin.py
If this is omitted, only the first character of an error is highlighted, since the error plugin (ALE in this case) doesn't know the end location.
> vim: Pass end of error location to enable highlighting of errors

- vim/merlin/autoload/merlin_find.vim
- vim/merlin/autoload/merlin_type.vim
- vim/merlin/autoload/merlin_visual.vim
VimL comparison operators without a trailing `#` (case-sensitive) or `?` (case-insensitive) inherit the user's current settings.
Specifying a particular case sensitivity does not affect the behavior when the arguments are integers.
> use case sensitive comparison vim

- emacs/merlin.el
Currently, Merlin does not follow the Emacs convention of having the `q` key quit a pop-up buffer. This is a bit of a hack, so I'm willing to rework it into having a proper key map for the types buffer that contains the binding.
> Standard q behavior for types buffer in emacs

- merlin.install
- vim/merlin/autoload/neomake/makers/ft/ocaml.vim
- vim/merlin/autoload/neomake/ocaml.vim
I couldn't get the Neomake integration working, and it would seem that the problem was:
1) The `.vim` file was not included in `merlin.install`
2) Neomake expects filetype makers to be inside `autoload/makers/ft` directory
I've tried only solving 1 but it didn't work, and only after 2 is fixed that it works perfectly.
I also added `EnabledMakers` function so that users wouldn't need to add any configuration to get it working. Let me know if this is considered too intrusive (previously we need to add `let g:neomake_ocaml_enabled_makers = ['merlin']` to `.vimrc`).
Also pinging @statianzo as the original author.
> Fix Neomake autoload

- src/utils/sexp.ml
The for loop was not updated in #758
Therefore backslashes are usually not escaped. This should finally fix #744
> fix escape sexp

- vim/merlin/autoload/merlin.py
Umlauts in filepath led to errors after switching from Ubuntu to Manjaro while loading the plugin.
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdc' in position 34: ordinal not in range(128)
Encoding the ```fnames``` fixes said issue.
> [autoload/vim] Fix umlaut issue in filepaths on manjaro

- src/ocaml/typer_406/typing/env.ml
- src/ocaml/typer_406/typing/env.mli
- src/ocaml/typer_406/typing/predef.mli
- src/ocaml/typer_406/typing/printtyp.ml
- src/ocaml/typer_406/typing/short_paths.ml
- src/ocaml/typer_406/typing/short_paths.mli
- src/ocaml/typer_406/typing/short_paths_graph.ml
- src/ocaml/typer_406/typing/short_paths_graph.mli
- src/ocaml/typer_406/typing/typeclass.ml
- src/ocaml/typer_406/typing/typedecl.ml
- src/ocaml/typer_406/typing/typemod.ml
- src/ocaml/typer_406/typing/typemod.mli
Needed some changes to work with the new approach to `open`, but otherwise it's the same as the patch for 4.05.
> Use new short paths with 4.06

- emacs/merlin.el
Correctly set face of content of `*merlin-types*` when type comes from reason file.
> emacs: support reason-mode in *merlin-types* buffer

- emacs/merlin-company.el
- emacs/merlin.el
* prefer string-match-p over string-match when we don't need match data
* use save-match-data to restore match data just in case. This is done a bit defensively in some cases, but it causes no harm to leave it in.
> Cleaner handling of emacs match data

- vim/merlin/autoload/merlin.py
The usage of the `enclosing_types` cache in the Vim plugin is pretty bugged — fixes #732, #770.
This is my first PR, so I intentionally went a bit overboard with explanatory comments; I also tried to match the code-style while moving things around.
I won't be offended at all if you have any feedback on how you want this cleaned up — feel free to throw any requirements at me if you want this massaged! `<3`
> Fixing vim's handling of the enclosing-type cache

- vim/merlin/autoload/merlin.vim
Otherwise the message is shadowed by the error caused by `call merlin#Register`.
> Use echoerr for error message in vim plugin

- vim/merlin/autoload/merlin.py
allows to "jump to definition" when project path has spaces
> vim: fnameescape path argument to vim commands

- dune-project
Otherwise `opam pin add merlin --dev` fails with:
```
...
...
```
> Add a dune-project file

- src/frontend/ocamlmerlin.c
- src/platform/os_ipc_stub.c
This fixes compilation under `mingw64`. cc @dra27
> msvc: use correct preprocessor macro

- emacs/dune
Likely forgotten in the migration to Dune.
> [emacs] fix `merlin-xref.el` install

- .travis.yml
- Makefile
- merlin.opam
- src/frontend/ocamlmerlin.c
- src/frontend/ocamlmerlin_server.ml
- tests/locate/non-local/dune
- tests/locate/partial-cmt/dune
- tests/merlin-wrapper-template
- tests/type-expr/test.t
The CI is in a somewhat dilapidated state (possibly a combination of Merlin 3.1 and last-minute Jbuilder/Dune ports?!).
This PR is a start at getting it back up and running - I'd like to bring the AppVeyor scripts up-to-date and have AppVeyor activated for this repo, but it's a difficult to maintain Windows ports when the official Unix ones are not in a pristine state too!
The commits not marked "WIP" are all finalised. I've switched Travis to the experimental Xenial images, the switch to `realpath` in the testsuite is a problem on Trusty, as it uses the old `realpath` package, rather than the coreutils one.
The testsuite running on various versions of OCaml is having trouble, which is what the WIP commits try to address. I've got an opam workspace set-up with those versions of OCaml - if …
> WIP: Restore CI

- emacs/merlin.el
This is a really useful feature that isn't widely known.
> Emacs: Document that merlin-type-enclosing can increase verbosity

- CHANGELOG.md
- README.md
- src/frontend/lsp/ocamlmerlin_lsp.ml
- src/lsp/dune
- src/lsp/uri.ml
- src/utils/std.ml
To be merged after #905.
- Remove dependency on stringext library.
- Update changelog and readme, add @andreypopp and @bryphe to the list of contributors.
> Lsp without stringext

- emacs/merlin.el
Also replace `add-to-list` with `push`, to conform to elisp best practices (see the docstring of `add-to-list`).
Before:
After:
> Emacs: Show the number of errors in the modeline

- vim/merlin/autoload/merlin_type.vim
In newer versions of neovim, assigning to`vim.current.window.cursor`causes a change in the viewport (#820). In these versions, changing the cursor isn't necessary in the first place, as it was a workaround for older versions of neovim.
This PR also contains an unrelated fix for unnecessary filling of the `:messages` buffer due to an unsilenced `buffer` command.
> Fix change of viewport after MerlinTypeOf in neovim

- src/lsp/rpc.ml
Tried hooking up the emacs lsp-mode client to merlin's LSP server and it expects the `jsonrpc` field in responses, as per the 'abstract message' part of the spec: https://microsoft.github.io/language-server-protocol/specification .
With this change the emacs client connects fine.
> lsp: add jsonrpc version field to responses as per spec

- src/ocaml/typing/403/btype.ml
- src/ocaml/typing/403/btype.mli
- src/ocaml/typing/403/env.ml
- src/ocaml/typing/403/env.mli
- src/ocaml/typing/403/typeclass.ml
- src/ocaml/typing/404/btype.ml
- src/ocaml/typing/404/btype.mli
- src/ocaml/typing/404/env.ml
- src/ocaml/typing/404/env.mli
- src/ocaml/typing/404/typeclass.ml
- src/ocaml/typing/405/btype.ml
- src/ocaml/typing/405/btype.mli
- src/ocaml/typing/405/env.ml
- src/ocaml/typing/405/env.mli
- src/ocaml/typing/405/typeclass.ml
- src/ocaml/typing/406/btype.ml
- src/ocaml/typing/406/btype.mli
- src/ocaml/typing/406/env.ml
- src/ocaml/typing/406/env.mli
- src/ocaml/typing/406/typeclass.ml
- src/ocaml/typing/407/btype.ml
- src/ocaml/typing/407/btype.mli
- src/ocaml/typing/407/env.ml
- src/ocaml/typing/407/env.mli
- src/ocaml/typing/407/typeclass.ml
- src/ocaml/typing/407_0/btype.ml
- src/ocaml/typing/407_0/btype.mli
- src/ocaml/typing/407_0/env.ml
- src/ocaml/typing/407_0/env.mli
- src/ocaml/typing/407_0/typeclass.ml
Move `Btype.unbound_class` to `Env` so that it appears after `Predef` in
the dependency order and doesn't change the identifier stamps of the
predefined identifiers.
> Re-align identifier numbers with compiler

- src/frontend/ocamlmerlin.c
- src/platform/os_ipc_stub.c
Actually there were not that much warnings from the clang static analyzer, beside the suggestion to use `strlcopy` instead of `strcopy` which is not available on all platforms.
The first warning is that the value of the `i += 1;` is never used which a simple scan through the source code can confirm.
The second warning comes the fact that `cm` is not tested for `NULL` and the corresponding path is given by
```
os_ipc_stub.c:128:15: warning: Access to field 'cmsg_len' results in a dereference of a null pointer (loaded from variable 'cm') [clang-analyzer-core.NullDereference]
int nfds = (cm->cmsg_len - CMSG_LEN(0)) / sizeof(int);
^
os_ipc_stub.c:258:12: note: Assuming the condition is false
} while (selectres == -1 && errno == EINTR);
^
os_ipc_stub.c:258:28: note: Left side of '&&' is false …
```
> Fixed warnings found by clang static analyzer.

- merlin-lsp.opam
This dependency is no longer required since #906
> Remove stringext from merlin-lsp.opam

- src/analysis/outline.ml
- src/frontend/query_json.ml
- src/frontend/query_protocol.ml
This adds type information for value bindings in `outline` query.
This allows to implement CodeLens like functionality. Example with neovim below:
> Return type info in module outlines

- .travis.yml
- tests-lsp/__tests__/textDocument-completion.test.ts
- tests-lsp/package.json
- tests-lsp/src/LanguageServer.ts
- Fixes tests for LSP frontend and makes deterministic (sort output of completion, not sure why it's different across machines but this is what original protocol tests are doing too)
- Add new job which tests LSP frontend with 4.07
> Run LSP tests on CI

- src/frontend/lsp/ocamlmerlin_lsp.ml
- src/lsp/protocol.ml
- src/lsp/rpc.ml
- src/lsp/rpc.mli
- tests-lsp/__tests__/textDocument-references.test.ts
Support `text/findReferences`, analogue of `occurances`
https://microsoft.github.io/language-server-protocol/specification#textDocument_references
/cc @andreypopp
> LSP: Add "Find references"

- src/frontend/query_commands.ml
- tests/occurrences/basic.ml
- tests/occurrences/basic.t
- tests/occurrences/dune
My first time contribution to merlin, don't know codebase at all so would appreciate some help!
This fixes `Occurrences` query to handle cases where queried identifier is annotated with type constraint:
```
let withTypeAnnot (some : int) =
some + some
```
I've also added general test cases for `Occurrences` query as a part if this PR.
> Fix Occurrences query to climb out of patterns with type constraints

- src/analysis/locate.ml
- src/analysis/locate.mli
- src/frontend/lsp/ocamlmerlin_lsp.ml
- src/frontend/query_commands.ml
- tests-lsp/__tests__/textDocument-definition.test.ts
- tests-lsp/__tests__/textDocument-typeDefinition.test.ts
Related to #885
Modifies `Locate.from_string` to accept `kind : [ Any | Type ]` argument:
- In case `Any` is passed then the original behaviour is used.
- In case `Type` is passed we try to lookup only types from environment.
Todo:
> Locate type at point

- src/frontend/lsp/ocamlmerlin_lsp.ml
- tests-lsp/__tests__/textDocument-completion.test.ts
This PR adds fills the `sortText` field of completion items in `textDocument/completion` response. This is necessary to make sure that the client will respect the order decided by merlin.
Tested on emacs only.
https://microsoft.github.io/language-server-protocol/specification#textDocument_completion
https://github.com/tigersoldier/company-lsp/issues/56#issuecomment-424593632
> Per [specification](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion), the server can specify `sortText` for each candidate. Candidates should be sorted by `sortText` if the server populates them, or sorted by the labels if `sortText` is not populated.
> LSP: provide sortText in completion items

- emacs/merlin.el
Previously the path to `ocamlmerlin` was built through prepending the result of `opam config var bin`. This works for the merlin binary itself, but if additional readers are used (such as ocamlmerlin-reason), merlin reverted to using the environmental path to look up the location of these binaries.
This means that if you have an reader on your global path that's incompatible with the current opam switch's merlin/ocaml version, merlin gets very unhappy.
This calls `ocamlmerlin` via `opam config exec` instead, which sets up the environment correctly and means it finds other merlin binaries in the switch as you'd expect.
> emacs: make sure PATH is updated when merlin-command is 'opam

- src/frontend/lsp/ocamlmerlin_lsp.ml
The content of `entry.info` is long and correspond to the documentation. The type (`entry.desc`) must be in detail to be displayed.
> LSP: switch detail and doc in completion answer

- src/frontend/lsp/ocamlmerlin_lsp.ml
- src/lsp/protocol.ml
- tests-lsp/__tests__/TextDocument.test.ts
- tests-lsp/__tests__/textDocument-hover.test.ts
- tests-lsp/src/LanguageServer.ts
I am not sure about this one. But I have the impression that the value returned by hover will always be some kind of ocaml/reason code. So the answer should be a MarkedCode instead of a MarkedString.
> LSP: change hover response from string to code

- src/frontend/lsp/ocamlmerlin_lsp.ml
- src/lsp/protocol.ml
- src/lsp/rpc.ml
- src/lsp/rpc.mli
- src/lsp/uri.ml
- src/lsp/uri.mli
- tests-lsp/__tests__/textDocument-rename.test.ts
The implementation is as complete as it could be, but it works for me. Tested in emacs and vscode.
- I did not implement all the parts of the yojson conversion that were not needed for rename support. So `WorspaceEdit` can be in a response but not a request. 
- I did not implemented all the `CreateFile | RenameFile | DeleteFile` types for `resource_operation` to be usable. They are not yet necessary for now as merlin doesn't work on multiple files. The type exist to reflect what is in the spec.
- in `WorkspaceEdit.changes` there is a hack to get a uri as a string. This is necessary because the spec for `changes` is `{ [uri: string]: TextEdit[]; }`.
- the capabilities of the client are not checked before to create the response, for now it always assumes that …
> LSP: add support for textDocument/rename

- vim/merlin/ftplugin/reason.vim
Hello and thanks for the work!
I think it would be useful to make merlin's vim plugin automatically
activate itself on Reason filetype buffers too. That was preventing
me from using it with a BuckleScript project recently.
> Activate on Reason file types

- src/frontend/lsp/ocamlmerlin_lsp.ml
- tests-lsp/__tests__/textDocument-hover.test.ts
If documentation is available, add it to the hover response.
I wonder if the doc should be surrounded with `(** *)` so that it gets nice highlighting.
> LSP: return doc on hover

- src/frontend/lsp/ocamlmerlin_lsp.ml
- src/lsp/protocol.ml
- src/lsp/rpc.ml
- src/lsp/rpc.mli
- tests-lsp/__tests__/textDocument-documentSymbol.ts
We check for hierarchicalDocumentSymbolSupport capability and returns a list of
document symbols instead of a flat list of symbol infos.
TODO:
> LSP: optionally return hierarchical document outline

- src/frontend/lsp/ocamlmerlin_lsp.ml
- src/lsp/protocol.ml
- tests-lsp/__tests__/textDocument-completion.test.ts
This PR adds support for expand-prefix in addition to completion-prefix in LSP. It should allow to complete invalid prefix such as `L.m` to `List.map`.
> LSP: add expand-prefix and labels support

- merlin-lsp.opam
- src/lsp/protocol.ml
As per spec those fields are marked as optional.
> LSP: add default values when decoding init request

- src/ocaml/preprocess/402/parser_raw.mlyp
- src/ocaml/preprocess/402/parser_recover.ml
- src/ocaml/preprocess/403/parser_raw.mlyp
- src/ocaml/preprocess/403/parser_recover.ml
- src/ocaml/preprocess/404/parser_raw.mlyp
- src/ocaml/preprocess/404/parser_recover.ml
- src/ocaml/preprocess/405/parser_raw.mlyp
- src/ocaml/preprocess/405/parser_recover.ml
- src/ocaml/preprocess/406/parser_raw.mlyp
- src/ocaml/preprocess/406/parser_recover.ml
- src/ocaml/preprocess/407/parser_raw.ml
- src/ocaml/preprocess/407/parser_raw.mlyp
- src/ocaml/preprocess/407/parser_recover.ml
- src/ocaml/preprocess/recover/recover_attrib.ml
- tests/recovery/test.t
This PR address bug #940. The bug had two parts:
- computation of recovery costs was incorrect for non-parameterized tokens
- `<-` was picked because it had a null recovery cost (making it a favorite candidate for the parser), which led to problematic recovery decisions.
The first fix might affect other recovery decisions. I will test this branch for some time to ensure this does not introduce any regression.
> Lessminus recover

- src/frontend/lsp/ocamlmerlin_lsp.ml
They are cheap in merlin so no need to cache them.
> LSP: remove caching for config/source

- emacs/merlin-company.el
This is the default behaviour for many company backends, so provide an
option to make company-merlin behave similarly.
----
This is a follow-up to #939. I apologise for not responding last time. This does not change the default, but I'd really like the option to disable merlin completion inside strings.
> Emacs: Allow users to disable completion inside comments and strings

- emacs/merlin.el
This silences a byte-compiler warning and makes reflection with boundp
unnecessary. No functional change.
This is a minor refactoring as requested in #910 :)
> Define merlin-opam-bin-path a variable

- src/frontend/query_commands.ml
- src/ocaml/parsing/403/builtin_attributes.ml
- src/ocaml/parsing/404/builtin_attributes.ml
- src/ocaml/parsing/405/builtin_attributes.ml
- src/ocaml/parsing/406/builtin_attributes.ml
- src/ocaml/parsing/407/builtin_attributes.ml
- src/ocaml/parsing/408/builtin_attributes.ml
- src/ocaml/typing/402/typetexp.ml
Merlin treats parser errors differently: since it recovers and tries to do a best effort parsing after an error, the errors that will come after a parsing one are likely to be noise (due to unfortunate choice of the recovery algorithm).
This is ok for completion, typing, etc, as the environment will be at least as precise as what we had before the error, but not for the error reporting feature, which needs to filter errors that come after a parsing one. 
While Merlin has its own classification of errors, the `source` field from `Location.error` also indicates the source of an error. Use that and also mark `merlin.syntax-error` extension nodes as coming from the `Parser`.
This enables Reason (... and other alternative frontends) to communicate error classes to Merlin (distinguishing proper …
> Use Location.Source to classify errors

- src/analysis/browse_tree.ml
- tests/occurrences/dune
- tests/occurrences/issue827.ml
- tests/occurrences/issue827.t
Added the reproduction case of #827, and some other calls on the same file (which do work).
If in the call to `same_constructor` in `Browse_tree` I replace `env` by `t.t_env` then the initial bug is fixed but the working calls become broken.
It might be possible to choose which environment is best in every situation. But... I can't be bothered. So when the first one raises, I just try the other one.
Improvements welcome.
> occurences: I don't know which environment to use

- CHANGELOG.md
- doc/dev/ARCHITECTURE.md
- doc/dev/CACHING.md
- doc/dev/OLD-PROTOCOL.md
- doc/dev/PROTOCOL.md
- doc/next/Protocol.wiki
- emacs/merlin.el
- src/analysis/completion.ml
- src/analysis/destruct.mli
- src/analysis/typedtrie.ml
- src/frontend/new/new_commands.ml
- src/kernel/mconfig.ml
- src/kernel/mconfig.mli
- src/kernel/mreader_lexer.ml
- src/lsp/protocol.ml
- src/lsp/rpc.ml
- tests/locate/partial-cmt/test.t
- tests/locate/sig-substs/basic.t
- vim/merlin/autoload/merlin.py
- vim/merlin/autoload/merlin_type.vim
- vim/merlin/doc/merlin.txt
Typos found with https://github.com/codespell-project/codespell
Note:  "upstream" & "src/ocaml" skipped.
> Fixing misspellings

- emacs/merlin.el
The first patch will help debugging emacs related problems.
The second patch fixes #975: `(current-column)` is a "visual notion" (it depends on the width of tabs), which makes sense only inside emacs, while `(- (point) (line-beginning-position))` will compute the offset as a number of character.
> Emacs fixes: log arguments in merlin-debug-last-commands, compute line offsets correctly 

- src/ocaml/merlin_specific/408/browse_raw.ml
- tests/type-enclosing/dune
- tests/type-enclosing/letop.ml
- tests/type-enclosing/letop.t
> Browse tree: improve support for letop

- .travis.yml
I added 4.08 and removed 4.04, 4.05 and 4.06: if 4.02 and 4.08 build, they should all build.
I left:
- 4.03 because that's the first version we run tests on.
- 4.07 because it's necessary for lsp
> travis: update build matrix

- src/ocaml/typing/408/ident.ml
- src/ocaml/typing/408/ident.mli
- src/ocaml/typing/408/printtyp.ml
This issue appears when completing an empty identifier, e.g. `let foo = ‸` or `let foo = List.‸`.
I haven't diagnosed the root cause for the failure, but just silencing this `fatal_error` seems fine for now.
> ignore Ident.rename failures

- Makefile
- dune-workspace.test
- src/analysis/completion.ml
- src/ocaml/typing/402/oprint.ml
- src/ocaml/typing/403/oprint.ml
- src/ocaml/typing/404/oprint.ml
- src/ocaml/typing/405/oprint.ml
- src/ocaml/typing/406/oprint.ml
- src/ocaml/typing/407/oprint.ml
- src/ocaml/typing/407_0/oprint.ml
- src/ocaml/typing/408/oprint.ml
- tests/completion/dune
- tests/completion/parenthesize.ml
- tests/completion/parenthesize.t
Identifiers that are infix operators (`+`, `::`, ... `mod`) are no longer parenthesized during completion.
This PR improves that.
> Parenthesize

- src/kernel/mconfig_dot.ml
This is an amendment of f8365ccf0172c6908cd2 which was slightly wrong due to a misleading variable name.
> Mconfig_dot: filter files starting with dot from expand_glob (fix #979)

- emacs/merlin-imenu.el
That's what JSON look like for outline:
```
{
"start": { "line": 181, "col": 0 },
"end": { "line": 213, "col": 48 },
"name": "pp_all",
"kind": "Value",
"type":
"...",
"children": []
}
```
`children` are now at idx 6. Current code fails with `Wrong type argument: listp` when tries to call `parse-outline-tree` on a `type` string.
> Fix merlin-imenu

- src/frontend/new/new_commands.ml
It was mentioning search-by-polarity instead.
> Fix doc of refactor-open

- src/lsp/protocol.ml
With latest version of coc.nvim, merlin-lsp fails with unsupported fields in the didChange message : 
```
recv: {
"jsonrpc": "2.0",
"method": "textDocument/didChange",
"params": {
"bufnr": 1,
"original": "",
"textDocument": {
"version": 5,
"uri": "file:///home/joris/git/master/v2/backlinks_index.ml"
},
"contentChanges": [
{
"range": {
"start": { "line": 34, "character": 14 },
"end": { "line": 34, "character": 14 }
},
"rangeLength": 0,
"text": "_t1;\n          link_prev"
}
]
}
}
time elapsed processing message: 0.003816s
Protocol.DidChange.didChangeTextDocumentParams
```
the bufnr and original fields do not seem to be specified  https://microsoft.github.io/language-server-protocol/specification#textDocument_didChange but most of the other messages use `strict = false` while this one use …
> lsp: fix coc.nvim compatibility

- merlin-lsp.opam
- src/frontend/lsp/ocamlmerlin_lsp.ml
This PR do a few fixes to allow the merlin-lsp package to compile on 4.08 (it's now possible since deriving yojson has been ported to 4.08).
> Fix merlin-lsp 4.08 compilation

- src/kernel/mconfig.ml
- src/ocaml/utils/406/config.ml
- src/ocaml/utils/407/config.ml
- src/ocaml/utils/407_0/config.ml
- src/ocaml/utils/408/config.ml
Fixes https://github.com/ocaml/merlin/issues/977
> Enable safe-string if it's the default in the current version of OCaml

- emacs/merlin-xref.el
When `loc.file` is **not** the current file, `(merlin/make-point pos)` tries to find the requested pos in the current file, may fail and return null. This null propagated to `merlin-xref--line` causes an error `Wrong type argument: integer-or-marker-p, nil`
So, let's switch to the correct file before invoking `(merlin/make-point)`.
> Fix merlin-xref

- emacs/merlin.el
Otherwise, restarting the server after changing `merlin-command` has no effect, because the old value for `merlin-command` is cached in `merlin-buffer-configuration`.
> Emacs: reset configuration in all buffers when stopping the merlin server

- emacs/dune
- emacs/merlin.el
It is possible for the config to change independently from the buffer (because the external environment changed), in such situations, the user currently has to manually clear the cache to get back into a working state.
This PR offers a way to prevent the config from being cached, enforcing that the grouping function is called on every request.
(In an ideal setup, the grouping function does its own caching and is aware of environment changes).
Requested by @m-plamann.
> emacs: no conf caching

- emacs/merlin-imenu.el
@Wilfred @taquangtrung  could you have a look.
I'm also worried about these two lines:
```
;;; enable depth and size threshold for OCaml modules with big size
(setq max-lisp-eval-depth 10000)
(setq max-specpdl-size 10000)
```
I'm really not a fan of changing settings like that in some random emacs lisp script. Can we rewrite the code to avoid mutual recursion instead?
> Merlin imenu cleanup

- emacs/merlin-imenu.el
Don't recurse on the outline list, as large files have a long list and Emacs runs out of stack.
This ensures that merlin-imenu doesn't need to change Emacs stack depth settings (see discussion in #1021).
Also rename variables to ensure they're appropriately namespaced.
> Emacs: fix stack overflow on large files

- README.md
- appveyor.sh
- merlin-lsp.opam
- merlin.opam
- src/frontend/old/old_IO.mli
- src/frontend/old/old_protocol.ml
- src/lsp/rpc.ml
- src/lsp/rpc.mli
- src/lsp/uri.mli
Eliminates following warnings:
```
ocamlc src/frontend/.ocamlmerlin_server.eobjs/old_protocol.{cmi,cmo,cmt}
File "src/frontend/old/old_protocol.ml", line 97, characters 16-25:
Warning 3: deprecated: Std.Json.json
json types are being renamed and will be removed in the next Yojson major version. Use type t instead
ocamlc src/frontend/.ocamlmerlin_server.eobjs/old_IO.{cmi,cmti}
File "src/frontend/old/old_IO.mli", line 37, characters 22-31:
Warning 3: deprecated: Std.Json.json
json types are being renamed and will be removed in the next Yojson major version. Use type t instead
File "src/frontend/old/old_IO.mli", line 39, characters 48-57:
Warning 3: deprecated: Std.Json.json
json types are being renamed and will be removed in the next Yojson major version. Use type t instead
File …
```
> remove deprecation warning

- dune-workspace.template
- src/ocaml/parsing/408/ast_helper.ml
- src/ocaml/preprocess/402/parser_raw.ml
- src/ocaml/preprocess/403/parser_raw.ml
- src/ocaml/preprocess/404/parser_raw.ml
- src/ocaml/preprocess/405/parser_raw.ml
- src/ocaml/preprocess/406/parser_raw.ml
- src/ocaml/preprocess/407/parser_raw.ml
- src/ocaml/preprocess/408/parser_raw.ml
- src/ocaml/preprocess/408/parser_raw.mly
- src/ocaml/typing/408/env.ml
- src/ocaml/typing/408/env.mli
- src/utils/menhirLib.ml
- src/utils/menhirLib.mli
This PR addresses the bug reported by @nojb in #1032
> Fix issue 1032

- src/frontend/lsp/ocamlmerlin_lsp.ml
Whenever the server crashes, it should output the backtrace by default.
> [lsp] enable backtraces in server

- tests/merlin-wrapper-template
The sed that comes with OSX doesn't work in this case. 
This RP is required to run the tests on OSX.
> Use gsed on OSX

- emacs/merlin.el
`M-x merlin-occurrences` was broken in #888, because `merlin-occurrences-populate-buffer` relied on the side effect of moving point.
This meant that selecting results in the `*merlin-occurrences*` did not move point to the relevant line.
Also fix the style of line numbers so they're distinct from source code.
> Emacs: fix merlin-occurrences

- tests/file-cache/dune
While building merlin-lsp dune evals `(deps ...)` stanza and fails on
references to `%{bin:ocamlmerlin}` and `${bin:ocamlmerlin-server}` which
(by design) are not present in merlin-lsp package.
This commit marks `run-server-test` alias as being related to merlin
package so it's not considered while building merlin-lsp at all.
> Mark file-cache tests as related to merlin package

- merlin-lsp.opam
- merlin.opam
* The names are already present in the opam filenames
* Manually specified versions eventually become out of date
> Remove names and versions from opam files

- src/frontend/ocamlmerlin.c
`execvp()` cannot be reliably used under Windows because it's implemented via `CreateProcess()` and a child process does not replace the parent one.
> Fix 'old-protocol' frontend under Windows

- dune-project
- src/analysis/dune
- src/frontend/dune
- src/frontend/lsp/dune
- src/frontend/ocamlmerlin/dune
- src/kernel/dune
- src/lsp/dune
- src/ocaml/preprocess/dune
Dependencies should be specified explicitly without relying on
transitive deps.
> Disable implicit_transitive_deps

- tests/dune.inc
- tests/gen/gen_tests.ml
- tests/test-dirs/locate/context-detection/environment_on_open_bad.t
- tests/test-dirs/locate/issue802/test.t
* Deterministic order of tests. Sort tests before generating stanzas.
* Restore accidentally deleted .merlin file
> Test fixes

- tests/test-dirs/locate/includes/test.t
- tests/test-dirs/locate/issue845/test.t
- tests/test-dirs/motion/phrase.t
This should save people time debugging. It also caught some silent errors
in some tests. The commit history describes includes the details
> Print argument parsing errors

- src/ocaml/parsing/408/pprintast.ml
- src/ocaml/parsing/409/pprintast.ml
- src/ocaml/preprocess/409/parser_raw.ml
- src/ocaml/preprocess/409/parser_raw.mly
- tests/test-dirs/no-escape/test.t
Before this PR:
- one error was never caught on 409 (i.e. the exception & backtrace reached the user).
- some errors were caught and never reported on both 408 and 409.
> Properly report syntax errors on 408 and 409

- src/frontend/query_commands.ml
The final_config is obtained from the scope above and as far as I can
tell, is not going to change.
> Remove extra config binding

- src/analysis/completion.ml
- src/analysis/type_utils.ml
- src/analysis/type_utils.mli
- src/frontend/ocamlmerlin/query_json.ml
- src/frontend/query_commands.ml
- src/frontend/query_protocol.ml
- tests/dune.inc
- tests/test-dirs/completion/expansion.t
- tests/test-dirs/completion/parenthesize.t
- tests/test-dirs/deprecation/foo.mli
- tests/test-dirs/deprecation/run.t
- tests/test-dirs/deprecation/x.ml
- tests/test-dirs/polarity-search/older.t
- tests/test-dirs/polarity-search/recent.t
LSP clients are able to display deprecated completion suggestions as ~~strike
through~~. Hence it's useful to pass this information through.
The current implementation is a bit too simplistic. We need to make sure that it
works for various completion suggestions.
> Detect deprecation from attributes

- tests/dune.inc
- tests/test-dirs/locate/issue949/issue949.ml
- tests/test-dirs/locate/issue949/run.t
Looking up the definition of `+.` fails. This is because `Longident.parse` fails
to parse this identifier correctly.
> Reproduce #949

- src/ocaml/typing/409/env.ml
- src/ocaml/typing/409/persistent_env.ml
- src/ocaml/typing/409/persistent_env.mli
- tests/test-dirs/short-paths/dep.mli
- tests/test-dirs/short-paths/test.ml
- tests/test-dirs/short-paths/test.t
The 4.09 short-paths code had a FIXME. This PR fixes it.
Without this PR, `-short-paths` does not have access to any information from .cmi files -- so it doesn't work very well.
> Fix short-paths for 409

- src/ocaml/typing/402/ctype.ml
- src/ocaml/typing/402/ctype.mli
- src/ocaml/typing/402/typecore.ml
- src/ocaml/typing/403/typecore.ml
- src/ocaml/typing/404/typecore.ml
- src/ocaml/typing/405/typecore.ml
- src/ocaml/typing/406/typecore.ml
- src/ocaml/typing/407/typecore.ml
- src/ocaml/typing/408/typecore.ml
- src/ocaml/typing/409/typecore.ml
- tests/dune.inc
- tests/test-dirs/errors/error-in-constrained-env/test.ml
- tests/test-dirs/errors/error-in-constrained-env/test.t
When a type error occurs, recovery can sometime be done at an incorrect level. This happens because after the exception, calls to begin_def/end_def are not well bracketed.
This can lead to erroneous error messages, for instance in this example:
```
type _ gadt =
| I : int gadt
| S : string gadt
let show : type a. a gadt -> a -> string = function
| I -> string_of_int
| S -> None
```
We get:
`This definition has type 'a gadt -> 'a -> string which is less general than
'a0. 'a0 gadt -> 'a0 -> string`
In this PR, we propose to fix this problem by always saving and restoring levels when recovering from a type error.
> Error in constrained env

- src/frontend/query_commands.ml
- src/ocaml/merlin_specific/402/browse_raw.ml
- src/ocaml/merlin_specific/403/browse_raw.ml
- src/ocaml/merlin_specific/404/browse_raw.ml
- src/ocaml/merlin_specific/405/browse_raw.ml
- src/ocaml/merlin_specific/406/browse_raw.ml
- src/ocaml/merlin_specific/407/browse_raw.ml
- src/ocaml/merlin_specific/408/browse_raw.ml
- src/ocaml/merlin_specific/409/browse_raw.ml
- tests/dune.inc
- tests/test-dirs/type-enclosing/cons.ml
- tests/test-dirs/type-enclosing/cons.t
Given the following file:
```ocaml
type t = U
type t' = U
let f : t  = U
```
The type hint given by Merlin for the `U` occuring in `f` is `t'` instead of `t`.
The same problem happens in patterns.
- Refactor the `Browse_raw.fold_node` so that `exp_extra` nodes are considered children of their corresponding expression and not parents.
- Short the heuristic for type enclosings when the type can be directly extracted from the node.
> Fix wrong type information for constructors under type coercions

- src/kernel/mconfig.ml
Currently locate won't jump to locations in the standard library because it is not part of the source path.
Arguably the stdlib directory is a build directory not a source directory, but since it includes the `.mli` files alongside the `.cmti` files it makes sense to treat it as if it were a source directory.
> Include the stdlib in the source path

- tests/test-dirs/locate/context-detection/field.ml
- tests/test-dirs/locate/context-detection/field.t
When looking up an identifier that is being punned to a field, this
confuses merlin.
> Add reproduction case for punned field lookup

- tests/dune.inc
- tests/test-dirs/type-enclosing/module_type.mli
- tests/test-dirs/type-enclosing/module_type.t
Given an `.mli` with:
```ocaml
module type T = sig type a end
module T : sig type b end
include T
```
type-enclosing on the last `T` will return the module type `sig type b end` when it should give `sig type a end`.
This PR adds a test demonstrating this issue.
> Type-enclosing gives a module when it should give a module type

- vim/merlin/autoload/merlin.vim
This slightly changes the heuristic used to detect the version of python Merlin mode can use.
This should fix #1050.
> vim: rework python version detection

- src/ocaml/typing/408/typemod.ml
- src/ocaml/typing/409/persistent_env.ml
- src/ocaml/typing/409/typemod.ml
- src/ocaml/typing/410/persistent_env.ml
- src/ocaml/typing/410/typemod.ml
- tests/test-dirs/no-escape/test.t
- tests/test-dirs/no-escape/test_open.ml
- tests/test-dirs/no-escape/test_use.ml
Running Merlin in an invalid environment (containing interfaces from older version of OCaml, or corrupted ones) would let a top-level failure escape. It is now caught and handled like a normal typing error.
This behavior is also tested to prevent future regressions.
Note: I discovered that `Location.none` has changed in recent versions of OCaml (default line used to be -1, it is now taken from `Lexing.dummy_pos` which defines it as 0). That might lead to surprising behaviors in ppx that rely on omp for instant. Too hard to regularize tests, I rely on jq to filter discrepancies.
> Catch errors escaping from `Typemod.initial_env` for 4.08, 4.09 and 4.10

- src/kernel/mpipeline.ml
- tests/dune.inc
- tests/test-dirs/typer-cache/test.ml
- tests/test-dirs/typer-cache/test.t
Instances of the typechecker are cached based on configuration (values of type `Mconfig.t`).
Older versions of Merlin ignored some components resulting in possible mismatches between the internal configuration of the typechecker (loadpath, global modules visible from the environment) and Merlin configuration.
This patch just use the whole configuration as caching key.
> Stricter typechecker caching policy

- src/analysis/locate.ml
- src/analysis/locate.mli
- src/frontend/ocamlmerlin/new/new_commands.ml
- src/frontend/ocamlmerlin/query_json.ml
- src/frontend/query_commands.ml
- src/frontend/query_protocol.ml
- tests/dune.inc
- tests/test-dirs/locate-type/a.ml
- tests/test-dirs/locate-type/run.t
The lsp frontend implements the ability to go to the type definition of
an expression. This requires some low level machinery, so it's moved to
merlin itself.
> Move go-to typedef to merlin

- src/analysis/completion.ml
- tests/dune.inc
- tests/test-dirs/completion/infix.ml
- tests/test-dirs/completion/infix.t
This fixes the completion bug described in https://github.com/ocaml/merlin/pull/1107 
Merlin was eliminating all completion contestant with a `-` in their name to prevent leakage of internal compiler-introduced names.
This PR restrict the check to names starting with `self-`, `selfpat-` and `*type-`. The last one may be useless ? It is to prevent types from Merlin's recovery to be suggested.
> Completion bug

- src/ocaml/preprocess/dune
Currently, attempting to build in profile release mode will
result in dune complaining about duplicate rules:
```
$ dune build --profile=release
Error: Multiple rules generated for
_build/default/src/ocaml/preprocess/parser_recover.ml:
- _build/.dune/default/src/ocaml/preprocess/dune:14
- _build/.dune/default/src/ocaml/preprocess/dune:39
```
This fixes compilation of merlin in a dune monorepo with
`dune build --profile=release`.  I'm not quite clear on why
the opam merlin package worked, as I thought `-p` activates
the release profile...
> dune: remove duplicated rules for profile=release

- merlin.opam
This change may fix the OPAM CI which otherwise runs tests in parallel on 31 jobs.
> Limit test jobs to one

- .github/workflows/main.yml
We need to invalidate the cache if the opam file changes.
(CI builds may still be a bit non-reproducible due to the absence of a lock file that could be hashed in the cache key)
> Add the hash of opam packages to the cache key

- src/analysis/outline.ml
- tests/test-dirs/outline/path.ml
- tests/test-dirs/outline/run.t
This should fix issue #971 : outline types are now printed using the local environment.
I don't know enough about LSP to test in this setting.
> Use local env when printing outline to benefit from -short-paths

- tests/test-dirs/pp/simple-pp.t
This fixes the issue encountered when testing merlin on FreeBSD:
```
#=== ERROR while compiling merlin.3.3.9 =======================================#
- File "tests/test-dirs/pp/simple-pp.t", line 1, characters 0-0:
-          git (internal) (exit 1)
- (cd _build/default && /usr/local/bin/git diff --no-index --color=always -u tests/test-dirs/pp/simple-pp.t tests/test-dirs/pp/simple-pp.t.corrected)
- diff --git a/tests/test-dirs/pp/simple-pp.t b/tests/test-dirs/pp/simple-pp.t.corrected
- index 639d0d2..ee0d5c8 100644
- --- a/tests/test-dirs/pp/simple-pp.t
- +++ b/tests/test-dirs/pp/simple-pp.t.corrected
- @@ -28,6 +28,7 @@
-    > let x : int = 42 \
-    > #endif \
-    > EOF
- +  cpp: warning: argument unused during compilation: '-E' [-Wunused-command-line-argument]
-    {
-      "class": …
```
> Testsuite: Add compatibility with clang when used as main C++ compiler

- CHANGES.md
- src/dot-merlin/dot-protocol/dot_protocol.ml
- src/dot-merlin/dot-protocol/dot_protocol.mli
- src/dot-merlin/dot_merlin_reader.ml
- src/kernel/mconfig_dot.ml
- tests/dune.inc
- tests/test-dirs/config/dot-merlin-reader/erroneous-config.t
- tests/test-dirs/config/dot-merlin-reader/quoting.t
This PR add better error reporting for the external readers.
Covered cases:
- External reader unexpectedly not-running:
- `A problem occurred with merlin external configuration reader. Check that 'dot-merlin-reader' is installed. If the problem persists, please file an issue on Merlin's tracker.`
- `A problem occurred with merlin external configuration reader. Check that 'dune' is installed and up-to-date. If the problem persists, please file an issue on Merlin's tracker.`
- Bad output from the external reader. That can happen if merlin tries to start `dune ocaml-merlin` with a version of dune that doesn't support this sub-command. Dune then prints it's help, which is not a valid csexp.
- `Merlin could not load its configuration from the external reader.  Building your project with 'dune' …
> Add error messages for external configuration readers and disable quoting

- src/ocaml/typing/409/btype.ml
- src/ocaml/typing/409/btype.mli
- src/ocaml/typing/410/btype.ml
- src/ocaml/typing/410/btype.mli
- src/ocaml/typing/411/btype.ml
- src/ocaml/typing/411/btype.mli
- src/ocaml/utils/409/load_path.ml
- src/ocaml/utils/410/load_path.ml
- src/ocaml/utils/411/load_path.ml
On these versions, the compiler backends weren't using `Local_store.Compiler` :scream:
> Fix use of local store from 409 to 411

- src/analysis/destruct.ml.new
- src/analysis/destruct.ml.old
- tests/dune.inc
- tests/test-dirs/destruct/basic.t
- tests/test-dirs/destruct/issue596.t
This fixes #596 
I guess that it is reasonable to assume that when `get_every_pattern` finds an unexpected parent that means we are not in a position where destruct is allowed.
> Issue 596: replace exception by "not allowed" message

- dot-merlin-reader.opam
This package currently fails on 4.12 with the following error:
```
#=== ERROR while compiling dot-merlin-reader.3.4.1 ============================#
```
I believe it should always be constrained if it uses compiler version dependent code.
> The dot-merlin-reader package is always only valid for a limited set of OCaml compilers

- .github/workflows/main.yml
It's recommended that you use a style such as `v1`.
https://github.com/avsm/setup-ocaml#how-to-specify-the-version
> Use avsm/setup-ocaml@v1 instead

- src/analysis/completion.ml
It's faster to gather a list of lists and flatten later.
It's unlikely this optimization is very impactful, but it doesn't complicate the
code either.
> Replace appending list in a fold

- emacs/dune
Fixes #1210 
The target of the incriminating rule is not used anywhere else in the project. It is very unlikely that is is used by anyone.
This PR removes the rule.
> Remove unused Emacs rule

- vim/merlin/autoload/merlin.py
- vim/merlin/autoload/merlin.vim
I added these as part of my debugging for #1202, but they have turned out to be generally useful and low-cost to add.
The commands behave as `MerlinLocate`, but jumping to either the implementation or interface regardless of the contents of `g:merlin_locate_preference`.
> Add MerlinLocateImpl, MerlinLocateIntf commands

- vim/merlin/autoload/merlin_type.vim
Neovim's CursorMoved semantics differ from Vim's:
Vim: After the cursor was moved in Normal or Visual mode.
Neovim: After the cursor was moved in Normal or Visual mode **or to another window**.
Because we do `exe l:cur . "wincmd w"` after setting up the auto-commands, in Neovim they would fire immediately, causing the type history window to instantly close. This patch defers the auto-command setup until after we've run `wincmd w`.
> Fix for Neovim's CursorMoved semantics

- src/ocaml/parsing/411/ast_helper.ml
- tests/test-dirs/errors/issue1222.t
Since OCaml 4.11 a new error is raised by the parser, this PR replaces the raising function by `Msupport.raise_error`.
Fix #1222
> Fix issue #1222

- src/analysis/context.ml
- src/analysis/context.mli
- src/analysis/locate.ml
- src/analysis/type_enclosing.ml
- src/analysis/type_utils.ml
- src/analysis/type_utils.mli
- src/frontend/query_commands.ml
- tests/test-dirs/type-enclosing/gadt_wrong.t
- tests/test-dirs/type-enclosing/issue1226.t
It shouldn't have been using `Mtyper.node_at` which doesn't necessarily return the node around the cursor (that's something that should also be looked at, at some point).
Funnily enough, we were only using `node_at` for the small enclosing, not when getting the type from the AST.
This PR:
- removes the call to `node_at` and reuses the same nodes as the rest of the analysis.
- unifies the printing of constructor types between `type-enclosing` and `type-expr` (by reusing the one of `type-expr`, which I deemed to be the better of the two)
> Type-enclosing wasn't always looking at the right node

- tests/test-dirs/type-enclosing/types.t/run.t
- tests/test-dirs/type-enclosing/types.t/types.ml
A follow-up on @trefis's request in #1216 to add some tests that show how `type-enclosing` with `verbosity=0` returns undesired types. 
These tests show the pattern that `type-enclosing` run on a type definition of a type with type param(s), it either returns type itself, e.g., for `type 'a t = 'a`, `type-enclosing` returns `type 'a t = 'a t`, or it returns just the type, e.g., for `type 'a v = Foo of 'a`, it returns `type 'a v` without the actual definition. This is probably not an exhaustive list of cases when `type-enclosing` returns a less desired type, but I hope this helps.
> Add type-enclosing tests

- tests/test-dirs/type-enclosing/types.t/run.t
This PR is in response to #1230 (cc @ulugbekna).
First, I discovered that after rebasing past #1232 (which was merged last week), all but one of the FIXMEs were indeed fixed (hurrah!).
The diff is visible in https://github.com/ocaml/merlin/commit/5125e54a7aa033d444514c3af1122076845d57b6.
As for the remaining FIXME, it doesn't look like a bug, but rather like the expected behavior of `-short-paths`.
You can see that if we remove that flag, the result is the one you seem to expect @ulugbekna.
However, going back to the initial discuss of `verbosity`'s value (started in #1216), you can also notice that with that flag, the result stays the same regardless of the verbosity level.
> type-enclosing result on type expressions

- dot-merlin-reader.opam
- merlin.opam
`ocaml-dune-lint` used by OCaml-CI checks that every libraries explicitly used by a project is listed in the opam file.
> Make OCaml-CI happy

- src/analysis/completion.ml
- src/analysis/completion.mli
- src/frontend/ocamlmerlin/new/new_commands.ml
- src/frontend/ocamlmerlin/query_json.ml
- src/frontend/query_commands.ml
- src/frontend/query_protocol.ml
- src/kernel/mpipeline.ml
- src/kernel/mpipeline.mli
- src/kernel/mreader.ml
- src/kernel/mreader.mli
- src/kernel/mreader_lexer.ml
- src/kernel/mreader_lexer.mli
- src/ocaml/preprocess/lexer_raw.mli
- src/ocaml/preprocess/lexer_raw.mll
- tests/test-dirs/completion/kind.t/run.t
- tests/test-dirs/completion/kind.t/test.ml
Alternative implementation of #1137
The code is very similar, but it's on an up-to-date merlin.
Also, it made me realize that all the plumbing @rgrinberg had implemented is actually necessary if you want to also list keywords added by extensions (which you can't if you just access `Lexer_raw.keyword_table`).
> completion: add "keyword" kind

- emacs/merlin.el
Adding a "when" argument is mandatory for define-obsolete-function-alias since emacs Emacs-23.1. If this is not added, emacs shows an error on startup (See Issue #1234).
NOTE: I'm guessing the functions are made obsolete in v2.5.4 (I simply looked at the "blame" date on github and matched with the version that was released after 28th Feb 2017) Maintainers may be able to provide a more accurate version/date for this argument
> Fixes #1234

- src/utils/misc.ml
These changes ensure that the `/ ` or `\` in the drive part of a Windows path (`c:\`) is correctly converted to the current platform separator.
It also always make the drive letter uppercase. This seems to be the standard (even if Windows understand both) and matches `Sys.getcwd ()` style.
This fixes communication issues between Merlin and Dune's `ocaml-merlin` configuration server on WIndows.
> Make canonical Windows paths more canonicals

- src/analysis/browse_misc.ml
- src/analysis/destruct.ml
- src/analysis/destruct.mli
- tests/test-dirs/destruct/dune
- tests/test-dirs/destruct/prefixing.t
(this PR targets branch 411)
This is an attempt to improve prefixing on Destruct and it will be reused by Construct.
We scan the environment to gather opened modules paths and then we use that information to drop prefixes in paths that are in the list of opened paths.
As suggested by @def, because over-shortening of the prefix can happen is some shadowing cases, we always check that the resulting lid can be found in the environment. If not we fallback on the non-shortened lid.
I made the function looking up in the environment a parameter of `Destruct.Path_utils.to_shortest_lid` in anticipation of Construct usages. For Destruct the lookup function if always `Env.find_constructor_by_name` but Construct will need more flexibility as it handles more diverse types of objects.
> Improve prefixing of Destruct by removing opened modules

- src/analysis/completion.ml
- src/ocaml/typing/typecore.ml
- tests/test-dirs/completion/disambiguation.t/constr.ml
- tests/test-dirs/completion/disambiguation.t/record.ml
- tests/test-dirs/completion/disambiguation.t/run.t
Type recovery on record degraded over the past few years, which in turns degraded completion results when inside a record expression.
I reintroduced a naïve recovery for record, but it needs to be reviewed (in particular: I am not calling `Msupport.erroneous_type_register`, should I?).
The other commit extends constructor completion candidates with the constructor from the expected type which matches the given prefix.
> Completion: use type information

- merlin.opam
Ocaml CI was running one 4.11 build because the constraint was `>4.11.1` and not `4.11.2`.
This PR sets the constraint to `>= 4.12.0`.
> CI fix attempt

- src/analysis/completion.ml
- tests/test-dirs/completion/infix.t/run.t
- tests/test-dirs/locate/ambiguity/not-in-env.t
#1276 broke two tests (and I didn't notice! :scream: ):
- one is due to me not considering the prefix when proposing disambiguated constructors as completion candidates. This PR fixes this
- the other is actually a very reasonable limitation of our current context detection, which is explained in the last commit. This became apparent because the typing recovery got slightly better. Before that the guessed context was "module path" which was definitely not correct. I didn't investigate why that was the case. The present result is more correct.
This PR should fix the CI! :pray:
> Fix test breakage

- src/frontend/ocamlmerlin/query_json.ml
- src/frontend/query_commands.ml
- src/frontend/query_protocol.ml
- src/ocaml/merlin_specific/browse_raw.ml
- src/ocaml/merlin_specific/browse_raw.mli
- tests/test-dirs/construct/holes.t
This PR updates the `holes` command to add the type of each hole to the returned value.
This can prevent supernumerary calls to Merlin from editors plugins. 
(see https://github.com/ocaml/merlin/pull/1287)
> Holes with types

- vim/merlin/autoload/merlin.py
- vim/merlin/autoload/merlin.vim
This PR add two new commands to the vim plugin : `MerlinNextHole` et `MerlinPreviousHole`
It also automatically jump to the first hole when destruct is called. This should allow nice chaining with Construct.
> [deconstruct][vim] Add next/previous hole commands

- README.md
Per the recent announcement (https://tarides.com/blog/2021-01-26-recent-and-upcoming-changes-to-merlin), .merlin files are not needed when using Dune.
> Clarify .merlin requirement in README

- .github/workflows/main.yml
This way both release and non-release modes are tested by the CI.
(OCaml-CI builds and test in non-release mode)
> Make GH Actions use release mode

- src/frontend/ocamlmerlin/ocamlmerlin.c
This suppresses a warning in mingw-w64.
> Constify argv parameter in _spawnvp

- src/analysis/destruct.ml
- src/frontend/query_commands.ml
- tests/test-dirs/destruct/errors.t
- tests/test-dirs/destruct/issue1300.t
Fixes #1300 
This PR adds graceful error handling for two cases:
- Recovered AST (#1300)
- No nodes
Future work: #1300 could be solved in a more satisfying way by improving the recovery
> Do not fail when destructing no-nodes or recovered nodes

- vim/merlin/autoload/merlin.py
Fixes #1302 
`sys.maxint` does not exists in Python 3 where ints do not have a maximum value.
It is used in the code to represent an value hypothetically higher than every over one so infinity (`float('inf')`) is correct value fir that. 
This PR also add the same "looping" behaviour as in the emacs plugin: if there is no next hole the first hole is returned (and vice et versa for "previous hole".
(There is some code duplication but I am not sure that it would be worth it to abstract like we did in the Emacs equivalent.)
> Use infinity instead of maxint. Loop holes like in emacs.

- emacs/merlin.el
- vim/merlin/autoload/merlin.py
- vim/merlin/autoload/merlin.vim
Merlin used to support the `-package` flag to load an ocamlfind/findlib package. This was exposed by the `:MerlinUse` and `merlin-use` commands in vim and emacs.
The commands are still there but the support for `-package` was dropped when packaging logic was moved to dune (via the reader helper). So they are broken in the latest release...
This PR reimplements the command so they work entirely on editor side: `ocamlfind` is invoked to list packages and resolve package names to include path. Only theses paths are passed to merlin using the `-I` flag.
Tradeoffs:
- ocamlfind is called from the editor environment... the answers might be out of date if the user changed to another opam switch. Workaround: maybe we should call `opam exec ocamlfind` instead of `ocamlfind`? (That's much slower... …
> vim & emacs : implement MerlinUse/merlin-use/-package in editor modes

- src/kernel/mppx.ml
Ppx are invoked only once so there is no need to manage cookies.
@lpw25 observed that restoring cookies cause the load path to be rescanned.
This doubles the number of uncached calls to stat which can be expensive on large projects.
This small change should increase performance and should not change any other behavior.
> Mppx: don't restore cookies after invocation

- src/analysis/locate.ml
- tests/test-dirs/src-documentation/run.t
Hi! 
Fixes #1261 
tl;dr `Ocamldoc.associate_comment` needs a list of doc-comments from the start to the end of file (non-decreasing positions of comments), but `Locate.get_doc` returned the comments from the end to the start of the file (non-increasing positions of comments). The last doc-comment was available because the last elem of non-decr list = head of non-incr list.
More detailed: 
`Ocamldoc.associate_comment` takes a list of doc-comments (with their positions) from a file and compares positions of those comments with the position `p` of the cursor. If a doc-comment `d` with position `p1` has `p1 > p` (ie documentation occurs later in the file than `p`), it considered there the list doesn't contain documentation for position `p`. (see …
> fix same file documentation bug

- CHANGES.md
This is the draft changelog for release 4.2-412 and the scheduled backports.
> Prepare for 4.2 release

- CHANGES.md
- src/analysis/destruct.ml
- src/ocaml/typing/typecore.ml
- src/ocaml/typing/typecore.mli
- tests/test-dirs/destruct/issue1300.t
- tests/test-dirs/typing-recovery.t
Introduce recovery on patterns.
Before this PR the recovery only happened at the granularity of an expression, so the whole pattern matching/function was lost.
After this PR, only the problematic pattern is lost.
Note: some care is required so destruct doesn't try to work with recovered patterns.
> Type error recovery: patterns

- src/ocaml/merlin_specific/browse_raw.ml
- tests/test-dirs/occurrences/pattern.t
For a pattern like `(x)`, merlin will include the parens in the locations. This
PR fixes changes the location to only include the identifier.
> Fix location of patterns in Occurrences

- src/analysis/context.ml
- src/analysis/context.mli
- src/analysis/locate.ml
- src/analysis/type_enclosing.ml
- src/frontend/query_commands.ml
- tests/test-dirs/type-enclosing/constructors_and_paths.t/run.t
- tests/test-dirs/type-enclosing/issue1116.t/issue1116.ml
- tests/test-dirs/type-enclosing/issue1116.t/run.t
This PR fixes #1116
If the context of a small enclosing is a string we do not try to type it anymore.
> [Based on #1108] Use context to prevent typing of small enclosings in strings

- tests/test-dirs/config/check/dune
- tests/test-dirs/config/dot-merlin-reader/dune
- tests/test-dirs/config/dune
- tests/test-dirs/config/flags/dune
- tests/test-dirs/dune
- tests/test-dirs/locate/ambiguity/dune
- tests/test-dirs/locate/context-detection/dune
- tests/test-dirs/locate/dune
- tests/test-dirs/locate/functors/dune
- tests/test-dirs/locate/local-definitions/dune
- tests/test-dirs/locate/non-local/dune
- tests/test-dirs/locate/reconstruct-identifier/dune
- tests/test-dirs/pp/dune
This ensures that `dune runtest` works on Windows: if Windows runners are added to ocaml-ci, this will not break the build, and failures can be fixed incrementally.
> Disable failing tests on Windows

- tests/test-dirs/type-enclosing/issueLSP444.t
This PR reproduce issue from ocaml/ocaml-lsp#444
```
type 'a t =
| A : [`A] t
| B : [`B] t
let f x =
match x with
| A -> ()
```
Wrongly triggers the following errors:
```
This pattern matches values of type [ `B ] t but a pattern was expected 
which matches values of type [ `A ] t Type [ `B ] is not compatible with type [ `A ]
```
```
Warning 8: this pattern-matching is not exhaustive. Here is an example of a case that is not matched: _
```
> Add test reproducing GADT issue from ocaml-lsp#444

- src/kernel/mconfig_dot.ml
Starting with Dune 3.0 the name `dune-file` will be able to be used instead  of `dune` for build configuration files.
This PR anticipate this change, and also fix an issue when `dune-workspace` file is used instead of `dune-project`.
> Dune file new name: "dune-file"

- CHANGES.md
- doc/dev/PROTOCOL.md
- src/analysis/construct.ml
- src/analysis/construct.mli
- src/analysis/ptyp_of_type.ml
- src/analysis/ptyp_of_type.mli
- src/frontend/ocamlmerlin/new/new_commands.ml
- src/frontend/ocamlmerlin/query_json.ml
- src/frontend/query_commands.ml
- src/frontend/query_protocol.ml
- src/ocaml/parsing/pprintast.ml
- src/ocaml/parsing/pprintast.mli
- src/ocaml/typing/typemod.ml
- tests/dune
- tests/test-dirs/construct/c-depth.t
- tests/test-dirs/construct/c-errors.t
- tests/test-dirs/construct/c-modules.t/functor_app.ml
- tests/test-dirs/construct/c-modules.t/module.ml
- tests/test-dirs/construct/c-modules.t/run.t
- tests/test-dirs/construct/c-objects.t
- tests/test-dirs/construct/c-parenthesis.t
- tests/test-dirs/construct/c-prefix.t
- tests/test-dirs/construct/c-simple.t
- tests/test-dirs/construct/dune
- vim/merlin/autoload/merlin.py
- vim/merlin/autoload/merlin.vim
- vim/merlin/doc/merlin.txt
This PR adds:
- a new command `construct` that given the position of a hole will return a list of possible expressions to fill this hole
- a handful of tests for that command
- the VIM plugin support for that feature:
+ `MerlinConstruct` on a hole `_` will open a completion dialog with the alternatives or replace the hole is only one construction is possible
+ One can ask to increase (or decrease) search depth with `c-i` (`c-u`) while choosing a completion
+ Once a completion is chosen it replaces the hole and the cursor jump to the next hole
Todo:
> [Construct] Part I 

- CHANGES.md
- emacs/merlin.el
New command: `merlin-construct` 
If multiple choices the basic completion buffer is used. 
After substitution the cursor jumps to the first hole in the constructed expression.
> [construct] Add basic emacs support

- dune-project
- merlin.opam
- tests/test-dirs/dune
This should fix random failures of the CI.
> Use locks for server related tests :tada: (require Dune 2.9)

- CHANGES.md
- src/frontend/query_commands.ml
- src/kernel/mbrowse.ml
- src/kernel/mbrowse.mli
- tests/test-dirs/refactor-open/qualify.t
- tests/test-dirs/refactor-open/qualify_short_paths.t
- tests/test-dirs/refactor-open/record_field.t
`refactor-open qualify` uses a "full path" to qualify modules, e.g., 
```ocaml
open Import (* calling refactor open qualify on this open does the following qualification, which is undesirable *)
let path = Dune__exe.Import.Option.value_exn (Dune__exe.Import.Unix_env.get Dune__exe.Import.Unix_env.initial "PATH")
```
I think this is not what a user wants when they use this command. 
This PR makes the command to qualify paths up to the leftmost ident in the open expression, e.g., up to `Import` in the above example despite the full path being `Dune__exe.Import.Option.value_exn`. 
Notes: 
- based on #1312 branch
- added before- and after-PR tests
- the tests concern only refactor-open qualify because the changes concern only refactor-open qualify 
- made minimal changes to keep PR easy to …
> refactor-open qualify uses short-paths

- src/analysis/construct.ml
- tests/test-dirs/construct/c-fun.t
Thanks @ulugbekna for signaling that issue.
Construct's argument name generation was a bit broken:
```
$ cat >fun1.ml <<EOF
> module Mymod = struct type the_type = int end
> let x : Mymod.the_type -> unit =
>   _
> EOF
$ $MERLIN single construct -position 3:2 \
> -filename fun1.ml <fun1.ml | jq ".value"
...
[
"(fun Mymod -> _)"
]       ^^^^^
]
```
This PR fixes this by using the last component of the path instead of the first.
> [Construct] fix generated argument names

- CHANGES.md
- src/frontend/query_commands.ml
- src/ocaml/parsing/location_aux.ml
- src/ocaml/parsing/location_aux.mli
- tests/test-dirs/refactor-open/unqualify.t
Before this PR `refactor-open` returns edits that when applied do not change the document, e.g, 
Calling `unqualify` on this:
```ocaml
open Unix 
let f = times () 
```
returned 
```ts
{
"class": "return",
"value": [
{
"start": {
"line": 2,
"col": 16
},
"end": {
"line": 2,
"col": 21
},
"content": "times"
}
],
...
}
```
This is a hacky solution though, which doesn't work for multi-line identifiers (which are rare in OCaml, I guess). A proper solution would involve changing `Mbrowse.node_paths` to return `longident`s along with paths. I would appreciate input on which way to go. 
Notes:
- Based on #1313 
- I'm sending these PRs separately since their goals are not interconnected (the commits are but that can be fixed easily)
> refactor-open: don't return useless edits

- src/ocaml/typing/typemod.ml
We have some users who are nondeterministically getting the error
```
error in process sentinel: merlin-mode failure: Uncaught exception Persistent_env.Error in initial_env.open_module: Persistent_env.Error(_)
```
We believe this to be due to a race with writing out `.cmi` files during the build process, and think it can be fixed by handling this exception in `Typemod.initial_env` in the same way other relevant errors are handled.
This change should probably be added to the "Backport to 3.4" and "Backport to 411" projects, but as I'm not a member of this repository I don't seem to be able to do that.
> Handle `Persistent_env.Error` in `Typemod.initial_env`

- emacs/merlin.el
* remove an Emacs 28 deprecation warning
* better error display
* avoid no-op buffer changes in refactoring
*
> Minor Emacs fixes

- doc/dev/PROTOCOL.md
- src/analysis/construct.ml
- src/analysis/destruct.ml
- src/analysis/destruct.mli
- tests/test-dirs/construct/c-fun.t
- tests/test-dirs/construct/c-simple.t
Thank you @ulugbekna for trying construct and noticing these issues.
Even if editor modes for emacs and vim don't use that feature yet, construct is able to look in the local environment for values whose type or return type is compatible with the current hole type.
Well, at least that is what the head of marketing said, but in practice this was mostly broken, and this PR attempts to fix it.
@ulugbekna could you test is with your shiny ocaml-lsp setup ? Even if I am still not convinced that we should enable this by default in the current form (showing all matching values) I am very interested by your feedback !
> [Construct] fix suggested values

- CHANGES.md
- src/frontend/ocamlmerlin/ocamlmerlin.c
On windows, if the username retrieved by `GetUserName` contain spaces, they end up in the socketname, and emacs fails when trying to open it.
> Replace spaces in socketname with '_'

- CHANGES.md
- src/analysis/refactor_open.ml
- src/ocaml/parsing/longident.ml
- src/ocaml/parsing/longident.mli
- tests/test-dirs/refactor-open/unqualify.t
`unqualify` previously could qualify, for example:
```
module M = struct
module N = struct
type t = Foo | Bar
end
end
open M (* unqualify [M] previously qualified [Foo] below into [N.Foo], which isn't what user wants I think *)
let v : N.t = Foo
```
The PR also uses a faster way to check if the new lident is different from the old one. 
Should be easiest to review commit-by-commit.
> Fix unqualify shouldnt qualify

- src/frontend/ocamlmerlin/new/new_merlin.ml
In `new_merlin.ml`, there's code to log the backtraces of exceptions for all non-`Failure` exceptions; this PR reorganizes things so that the backtrace is logged regardless of the variety of exception we have.
> Log the backtrace even when the exception is a `Failure`

- src/kernel/mconfig_dot.ml
In `Mconfig_dot`, there's a race condition around `waitpid` that can cause `ocamlmerlin` to crash if the process started to read a configuration file (either `dot-merlin-reader` or `dune`) crashes immediately or is not found.  This PR fixes that race condition; it also protects the PIDs behind a module abstraction boundary to prevent it from happening again.
The existing code could error in the following case (seven-point framing due to @stedolan):
1. We call `Mconfig_dot.get_config`.
2. On (the former) line 236, `get_config` calls `Mconfig_dot.Configurator.get_process`; this function spawns a process and stores its information in the `running_processes` hashtable.  (It doesn't matter which code path it goes down; let's suppose it starts it for the first time. i.e. the `with Not_found` …
> Avoid a race condition when the process started to read a configuration file crashes/is not found

- CHANGES.md
- src/kernel/mbrowse.ml
- tests/test-dirs/type-enclosing/merlin-hide.t
@lpw25 reported that type-enclosing would fail when called on `x` in
```ocaml
type t = { x : asdfasd } [@@deriving equal]
```
This PR fixes that.
> Mbrowse.select_leaf: correctly ignore merlin.hide

- src/kernel/mpipeline.ml
- src/kernel/mreader.ml
- src/kernel/mreader.mli
- src/ocaml/driver/pparse.ml
- src/ocaml/driver/pparse.mli
Merlin expects a source preprocessor `-pp` to return sources.
However, some existing preprocessors return marshalled ASTs.
This patch adds support for this situation, and should fix:
- https://github.com/ocaml/ocaml-lsp/issues/525
- https://github.com/ocaml/dune/issues/4169
- https://github.com/ocaml/merlin/issues/1246
Merlin functionalities will be reduced:
- recovery is up to -pp
- no support for placeholder insertion for completion
- lexer_ident will fallback to the unpreprocessed source to reconstruct
identifiers
> Allow -pp to return an AST

- tests/test-dirs/document/src-documentation.t/run.t
This is meant to be a bug-fix in the test suite.
Current behavior: when running the test-case, `dune` calls `ocamlopt` which in turns calls `ld`. In a particular context, I have a linker that emits a warning; this makes the test case fail (for a wrong reason).
Side note: if you want to see plenty of test failures, just `export OCAMLRUNPARAM='v=0x001'` before running the test suite…
> Ignore dune stderr in tests

- CHANGES.md
- src/ocaml/typing/typemod.ml
- tests/test-dirs/issue1322.t/.merlin
- tests/test-dirs/issue1322.t/foo.ml
- tests/test-dirs/issue1322.t/nasty.ml
- tests/test-dirs/issue1322.t/run.t
This cherry picks @lpw25 patch in ocaml/ocaml#10382.
Fixes #1322
> Don't repeat environment entries in Typemod.check_type_decl (ocaml/ocaml#10382)

- .gitignore
- src/analysis/locate.ml
- src/kernel/mconfig.ml
- src/utils/std.ml
[List.uniq] only dedups adjacent duplicates. This is sufficient for
[List.sort_uniq], but can be surprising when invoked directly. This commit
patches [List.uniq] to dedup the whole list. It is also now used when retrieving
source paths, which can be duplicates but for which we might want to preserve
ordering.
> Fix [List.uniq] to dedup non-adjacent elmements.

- CHANGES.md
- src/kernel/mocaml.ml
- src/kernel/mocaml.mli
- src/kernel/mpipeline.ml
- src/kernel/mppx.ml
- src/kernel/mppx.mli
- src/kernel/mreader.ml
- src/kernel/mreader.mli
- src/kernel/mtyper.ml
- src/ocaml/utils/load_path.ml
- src/utils/file_cache.ml
- src/utils/file_cache.mli
This PR makes 4 changes to speed up the handling of the load path:
1. It restores the use of Directory_content_cache for the load path -- which seems to have been removed by accident in the switch to 4.12.
2. It changes where 'Mocaml.setup_config` is called to ensure that it is only called once per command.
3. It uses a hash table for the load path instead of a reference to a map.
4. It reuses the previous hash table when the load path hasn't changed and none of it's directories' contents have changed.
On a randomly chosen command in a library with a large load path, each of these changes is worth around 0.1s. #1309 is also worth about 0.1s. Between them these changes take that command's runtime from 0.7s to 0.25s. (This is for the second call to the command, the initial call to the …
> Improve load path performance

- src/analysis/dune
- src/extend/dune
- src/frontend/dune
- src/frontend/ocamlmerlin/dune
- src/kernel/dune
- src/ocaml/merlin_specific/dune
- src/ocaml/parsing/dune
- src/ocaml/preprocess/dune
- src/ocaml/typing/dune
- src/ocaml/utils/dune
Allows loading things in utop and shouldn't increase the maintenance burden.
See the report in https://github.com/ocaml/ocaml-lsp/issues/557
> fix: wrap compiler-libs modules

- CHANGES.md
- src/ocaml/driver/pparse.ml
- src/platform/platform_misc.c
There's no need for quoting the files as we're not calling the ppx
through a shell.
Redirect the stderr of the child process to which of the parent (as
posix `system(3)`), and the stdout of the child to the stderr of the
child (as merlin's `ppx_commandline`).
Setting up the redirection in the parent process has the downside that
we must set the `bInheritHandles` flag of `CreateProcess`, which means
that if merlin leaks a handle (not setting it non-inheritable /
cloexec), the ppx process will have access to it.
cc @let-def @nojb
> Windows: correctly redirect stderr to stdout of called ppx 

- CHANGES.md
- src/frontend/ocamlmerlin/new/new_merlin.ml
- src/frontend/ocamlmerlin/ocamlmerlin_server.ml
- tests/merlin-wrapper
So far it was ankward to use the new dune-based configuration reader in the testsuite. The reason was that Merlin completely resets the environment and thus the `INSIDE_DUNE` variable was not forwarded to the spawned `.
This PR fixes that.
It might help to have a better testing story in #1219
> Allow the use of dune-base configuration reader in tests

- CHANGES.md
- tests/merlin-wrapper
- tests/test-dirs/document/dune
- tests/test-dirs/locate/dune
- tests/test-dirs/locate/issue1424.t
This is a reproduction test for issue #1424.
It is surprising that this test gives incorrect results while `locate/non-local/preference.t` does not.
The test uses the dune-based configuration reader and thus should be rebased after #1425 gets merged.
> Test issue1424

- CHANGES.md
- src/analysis/locate.ml
- tests/merlin-wrapper
- tests/test-dirs/pp/dot-pp-dot-ml-dune.t
- tests/test-dirs/pp/dot-pp-dot-ml.t
- tests/test-dirs/pp/dune
When ppx is used, the cmt sourcefile that is recorded is the *.pp.mli? file,
and we compare its digest to the digests of the files in the source directory.
Often the .pp.mli? file isn't there, and even when it is we probably do not
want to prefer it over the normal .mli? file for locate. This patch checks if
the file is a .pp.mli? file, and if so uses the digest of the regular .mli?
file instead.
> Fix [locate] to look for non-pp source files.

- CHANGES.md
- src/utils/marg.ml
- tests/test-dirs/alerts.t/run.t
#1401 introduced support for the `-alert` option of the compiler however it seems that the compiler accept the syntax `-alert=-deprecated` while Merlin doesn't. This PR add a test illustrating that.
The issue arised in dune: ocaml/dune#5245
@nojb Looking at #1401 I am not sure of what the issue is since it mostly reuses compiler's functions. But maybe Merlin in general rejects the `<option>=<arg>` syntax for all command line arguments (@trefis ?)
> test: flag `-alert` with `=` is not accepted by Merlin

- src/extend/extend_main.ml
- src/extend/extend_main.mli
As requested in https://github.com/ocamllabs/vscode-ocaml-platform/issues/818.
@rgrinberg The exception constructor has path `Extend_main.Handshake.Error`, is it ok? Anything else I can do to help vscode-ocaml-platform code?
> Add special exception for extension failure

- vim/merlin/autoload/merlin.vim
- vim/merlin/autoload/merlin_type.vim
This reverts commit 7efcb2265ed6525bf330666713f70cc83b32ce66.
The problem reported in #553 is not reproducible when this commit is reverted,
so it's likely that the underlying Neovim bug that caused it has been resolved.
The fix introduces a problem where the window is scrolled (#1221), so this
commit reverts it.
> Revert "fix #553"

- .github/workflows/main.yml
- src/ocaml/preprocess/parser_raw.ml
- src/ocaml/preprocess/parser_raw.mli
Apparently we missed some parser changes in master (thanks @ddickstein).
This PR adds a CI action to check the diff after building Merlin in non-release mode.
> Check parser update in CI

- CHANGES.md
- src/analysis/destruct.mli
This is required by OCaml-LSP to improve error handling. 
See https://github.com/ocaml/ocaml-lsp/issues/617#issuecomment-1035508467
cc @ulugbekna
> Expose the Ill_typed exception for pkgs using Merlin as a library.

- CHANGES.md
- src/frontend/ocamlmerlin/query_json.ml
- tests/test-dirs/errors/error-node-line-break.t
Following a report by @panglesd this PR fix an issue with the formating of errors.
The following node:
` [%%ocaml.error "test with several words"]`
is reported by the compiler as:
`Error: test with several words`
but by merlin as:
```
test with several
words
```
The difference is that Merlin uses `Location.print_main` to produce the string while the compiler uses `Location.print_report`. The latter function wrap the printing of the `main` part of the report in a pretty-printing box while the former doesn't.
This PR wraps the output of `Location.print_main` in a pp box.
> Fix superfluous break in error reporting

- CHANGES.md
- emacs/merlin-imenu.el
These are important syntactic categories, which I am missing a lot. In fact, the modules category is the most important as it enables to quickly move between submodules and significantly reduces cognition burden during developing OCaml programs. The class category fits into the same niche, except when the OOP style is employed. There is also a constructor category, though I am not really sure if is useful, and given that it can pollute the outline I decided to leave it.
> adds module, module type, and class imenu items

- CHANGES.md
- emacs/merlin.el
Currently, `merlin-locate` opens a new window if and only if the location is in another file.
However:
- When using `merlin-locate` several times in a row to find the definition we want, it can be annoying to have new windows erasing where we come from.
- Sometimes we want to keep the location we come from visible even if the definition is in the same file.
This PR gives the possibility to force a behavior, using the `prefix argument` mechanism:
- `C-u C-c C-l` force to stay in the same window, even if the cursor is moved to another file,
- `C-u C-u C-c C-l` force open another window, even if the cursor is moved the same file.
Other uses of the prefix defaults to the regular `C-c C-l`.
> Add prefix command to `merlin-locate` to open a new window.

- CHANGES.md
- src/kernel/mreader_lexer.ml
- src/ocaml/merlin_specific/browse_raw.ml
- src/ocaml/preprocess/lexer_ident.mll
- tests/test-dirs/locate/issue1398.t/issue1398.ml
- tests/test-dirs/locate/issue1398.t/run.t
- tests/test-dirs/occurrences/issue1398.t/issue1398.ml
- tests/test-dirs/occurrences/issue1398.t/run.t
Find binding operator uses in Occurrence and their definitions in Locate (issue #1398)
Although Locate works from a position where the binding operator syntax is used, Occurrence does not but requires the position to indicate the reified (bracketed) operator.
> Binding operators in occurrence and locate

- emacs/merlin-cap.el
- emacs/merlin-iedit.el
- emacs/merlin.el
Since Emacs 28, the elisp compiler warns on doc strings with lines
wider than 80 characters.
> Reformat elisp doc strings to silence compiler warnings

- CHANGES.md
- vim/merlin/autoload/merlin.py
- vim/merlin/autoload/merlin.vim
- vim/merlin/doc/merlin.txt
This PR refactors some functions in merlin.py to allow passing the mouse cursor position as input. In this way vim's balloonexpr functionality can be used to show the type at the mouse cursor. Hopefully this will be handy for browsing a codebase, where one does not necessarily wish to navigate the cursor to various places by keyboard commands.
Beware: the actualy popup window displayed by balloon-eval seems to be a bit flaky. I tested on two macos machines with identical MacVim version and identical .vimrc. The popup shows up only on one of the two. That is not a problem of merlin, as it fails also for the ALE plugin. The version with type display in the status line (or actually, below the status line? what is the bottom line of the screen called?) works in any case, so that should be a …
> Enable type-on-hover functionality in Vim

- CHANGES.md
- dot-merlin-reader.opam
- merlin.opam
- src/dot-merlin/dot-protocol/dune
- src/ocaml/utils/dune
- src/ocaml/utils/lazy_backtrack.ml
- src/ocaml/utils/lazy_backtrack.mli
- src/utils/dune
- src/utils/std.ml
As far as I can see, the `result` compatibility package is not required anymore
> Remove unused module and dependency

- README.md
- src/analysis/dune
- src/config/dune
- src/dot-merlin/dot-protocol/dune
- src/extend/dune
- src/frontend/dune
- src/frontend/ocamlmerlin/dune
- src/kernel/dune
- src/ocaml/merlin_specific/dune
- src/ocaml/parsing/dune
- src/ocaml/preprocess/dune
- src/ocaml/typing/dune
- src/ocaml/utils/dune
- src/platform/dune
- src/utils/dune
- tests/dune
Alternative to https://github.com/ocaml/merlin/pull/1448 and https://github.com/ocaml/merlin/pull/1172 to make the libraries public and wrap them under a single top-level module.
> Make merlin libraries public and wrapped

- emacs/merlin.el
close #1460 
when calling `merlin-locate`, if there was no prefix set, then `merlin-locate-in-new-window` was set to `'merlin-locate-in-new-window` rather than the actual value
> use unquoted merlin-locate-in-new-window with merlin-locate

- src/dot-merlin/dune
Silences the alert proposed in ocaml/ocaml#11198, but this PR can be merged regardless.
> Add missing dependency on Unix

- src/ocaml/typing/printtyp.ml
The paths in `Mty_alias` are module paths rather than module type paths, so should use `best_module_path`.
> Use `best_module_path` for paths from `Mty_alias`

- CHANGES.md
- README.md
- merlin.opam
- src/frontend/ocamlmerlin/old/old_IO.ml
Yojson 2.0 is dropping☨ the `Stream` API for compatibility with OCaml 5, thus it added an `Seq` based API. This PR does the small changes that are required to use it instead of `Stream`.
Which also comes with the added benefit of removing usage of `Stream` from Merlin itself.
☨Yojson 2.0 will drop the API when it is released. As such this PR requires the `master` version of Yojson but the idea is to prepare most Yojson consumers in advantage, so when Yojson 2.0 ends up on OPAM the migration is as smooth as possible.
> Use the Yojson 2.0 `Seq` API

- src/frontend/ocamlmerlin/log_info.ml
- src/frontend/ocamlmerlin/log_info.mli
- src/frontend/ocamlmerlin/new/new_merlin.ml
- src/frontend/ocamlmerlin/ocamlmerlin_server.ml
Notice how one splits `MERLIN_LOG` by `,` and passed sections while the other doesn't
> fix(logging): previously `ocamlmerlin_server.ml` and `new_merlin.ml` had different parsing for `MERLIN_LOG`

- CHANGES.md
- src/frontend/query_commands.ml
- tests/test-dirs/misc/load_path.t
- tests/test-dirs/type-enclosing/constructors_and_paths.t/run.t
- tests/test-dirs/type-enclosing/github1003.t/run.t
- tests/test-dirs/type-enclosing/issue1477.t
- tests/test-dirs/type-enclosing/letop.t/run.t
- tests/test-dirs/type-enclosing/mod-type.t/run.t
- tests/test-dirs/type-enclosing/objects.t/run.t
- tests/test-dirs/type-enclosing/record.t/run.t
- tests/test-dirs/type-enclosing/te-413-features.t
- tests/test-dirs/type-enclosing/types.t/run.t
- tests/test-dirs/type-enclosing/underscore-ids.t
Fixes #1477
The actual deduplication was not working as expected, probably due to a change of the types of the results that became incomparable.
> Fix types deduplication 

- CHANGES.md
- src/analysis/locate.ml
- src/ocaml/typing/shape.ml
- src/ocaml/typing/shape.mli
- tests/test-dirs/locate/dune
This prevent unnecessary computations when reducing shapes in Merlin.
For example, in the current released version, Merlin would completely reduce the whole shape of the module `Irmin_unix` when performing a jump-to-definition at `Irmin_u|nix.Git.Some(Stuff)` which is wasteful since we only need the UID attributed to the top-level structure of the shape.
This patch leads to a huge speed up in this case. Improving #1468 a lot.
cc @gasche
> Use weak strategy when reducing shapes

- src/dot-merlin/dot_merlin_reader.ml
- src/dot-protocol/merlin_dot_protocol.ml
- src/dot-protocol/merlin_dot_protocol.mli
- src/kernel/mconfig_dot.ml
- tests/test-dirs/config/unknown_tag.t
Dune configuration provider should never send unknown tags unless they have been meaningfully introduced.
In comparison unknown tag in an handwritten `.merlin` can result from a user's error.
This PR ignores unknown tags when Dune is used as a configuration provider. Since the protocol can only (so far) be grown additively this allow Merlin version that does not support a newer directive to simply ignore it.
> Ignore unknown tags from dune configuration reader

- CHANGES.md
- emacs/merlin.el
The `merlin-locate` command had a prefix argument added; it's elisp convention for prefix arguments to be optional, and this is especially helpful as the `merlin-locate` command is user-facing and this provides for backwards compatibility.
This change can also be backported to the 412 and 411 branches.
> Make the prefix argument to `merlin-locate` optional

- src/ocaml/typing/typemod.ml
- tests/test-dirs/outline-recovery.t
Fixes issue https://github.com/ocaml/ocaml-lsp/issues/841 reported for ocaml-lsp-server.
When typing of a module structure item failed the saved types from the structure were wrongly added to that sub module causing outline to misbehave:
```
$ cat >test.ml <<EOF
> module Make = struct
>   module A = struct end
>   module B = C.C1
>   module D = struct end
> end
> EOF
FIXME: A is not a child of B ! This is likely due to the typing recovery.
$ $MERLIN single outline -filename test.ml <test.ml
{
"class": "return",
"value": [
"name": "Make",
"children": [
"name": "D",
"children": [],
},
"name": "B",
"children": [
"name": "A",
"children": [],
}
],
},
"name": "A",
"children": [],
}
],
}
],
}
```
> Recovery caused nested outline

- CHANGES.md
- tests/test-dirs/document/label-comments.t
Add tests to document the current behavior, per https://github.com/ocaml/merlin/pull/1516#discussion_r1015460852
I can open an issue for the incorrect record field documentation if the reviewer agrees it's an issue. Seems similar to #1513 
https://v2.ocaml.org/manual/doccomments.html#ss:label-comments
> more test cases for label comment documentation

- CHANGES.md
- src/analysis/locate.ml
- src/analysis/ocamldoc.ml
- tests/test-dirs/document/issue1513.t
Fix #1513  Group doc comments for variant constructors only with only the constructor before
Reference:
https://v2.ocaml.org/manual/doccomments.html#ss:label-comments
> fix #1513: variant constructor docs 'only_after'

- CHANGES.md
- src/analysis/locate.ml
- src/ocaml/typing/typedecl.ml
- tests/test-dirs/document/issue1513.t
- tests/test-dirs/document/label-comments.t
- tests/test-dirs/locate/context-detection/cd-label.t/run.t
- tests/test-dirs/locate/dune
- tests/test-dirs/locate/issue1524.t
- tests/test-dirs/locate/locate-constrs.t
When querying jump to declaration of a record's label `foo.ba|r` merlin would only jump to the beginning of the corresponding record type declaration.
This is due to the uid's of labels not being registered by the compiler in the `Env.uid_to_loc` table.
This PR adds these uid registration to `typedecl.ml`. This means that the fix will only work for the current buffer and we would need to be upstreamed for it to work when jumping to external compilation units. 
cc @rgrinberg
> Improvement: jumping to a label's precise declaration.

- .github/workflows/emacs-lint.yml
- .github/workflows/main.yml
- emacs/check.sh
- emacs/merlin-ac.el
- emacs/merlin-cap.el
- emacs/merlin-company.el
- emacs/merlin-iedit.el
- emacs/merlin-imenu.el
- emacs/merlin.el
28.1 was recently released; `snapshot` tracks the development version (with some lag).
Oh, and `28.1` in YAML is a number so I prefer the quotes to make it a string just in case.
> Test Emacs parts on the released 28.1 as well

- src/platform/platform_misc.c
There are a couple of non-`#ifdef _WIN32` C functions that don't use their arguments; this PR marks those arguments as unused., silencing some warnings.
> Mark some C variables as unused

- CHANGES.md
- src/kernel/mconfig.ml
- tests/test-dirs/issue1518.t
This should fix #1518 
@kit-ty-kate do you no if other configuration options have been removed from OCaml 5 but are still accepted by the compiler as a no-op ?
> Accept the `-safe-string` flag but make it a no-op

- emacs/merlin.el
Whether a string literal is `eq` to anything else is undefined and, in this case, very unlikely: use `equal` instead. This silences a (well-justified) warning in Emacs 30, although the comparison may have been subsumed by the additional use of `merlin--error-warning-p` in practice.
> Broken `eq` comparison in merlin.el

- CHANGES.md
- emacs/merlin-xref.el
Fix uses of Xref from mouse events, such as the context menu new in Emacs 28, by implementing the necessary methods and smuggle the buffer position in a text property of the string.
We also get better highlighting of Xref hits in the target buffer by taking advantage of a bug fixed in Emacs 28.
> Emacs Xref improvements

- CHANGES.md
- src/ocaml/typing/magic_numbers.ml
And add an assertion that we can recognize our own magic number that we got compiled with.
Fixes https://github.com/ocaml/merlin/issues/1553
> Recognize OCaml 5.0 cmi magic number

- CHANGES.md
- src/analysis/type_enclosing.ml
- tests/test-dirs/type-enclosing/issue1564.t
- tests/test-dirs/type-enclosing/record.t/run.t
> Improve type-enclosing for record labels

- CHANGES.md
- src/kernel/mconfig.ml
These flags where added to OCaml 4.14 but are not accepted by Merlin.
Note for the 5.0 backport: the flag `-force-tmc` was removed in 5.0.
CC @antalsz
> Add missing ocamlc flags to the ignore list

- CHANGES.md
- src/analysis/locate.ml
- tests/test-dirs/locate/dune
- tests/test-dirs/locate/module-aliases.t/run.t
- tests/test-dirs/locate/module-decl-aliases.t
This PR implement a suggestion by @lpw25 to traverse module aliases when jumping to declaration.
> Jump to declaration through aliases

- CHANGES.md
- src/ocaml/typing/typecore.ml
- tests/test-dirs/locate/ill-typed/local-open.t
- tests/test-dirs/locate/ill-typed/locate-cannot-refute.t
- tests/test-dirs/locate/ill-typed/locate-non-fun.t
- tests/test-dirs/locate/ill-typed/not-a-function.t
- tests/test-dirs/type-enclosing/inside-tydecl.t
- tests/test-dirs/type-enclosing/underscore-ids.t
- tests/test-dirs/typing-recovery.t
This PR tracks the progress on fixing issue #1543.
Merlin tries to recover from typing errors, but large part of the typedtree are sometimes dropped. Fixing the error cases documented in #1543 requires improvement to the typing recovery.
> Locate fails in ill-typed expressions

- CHANGES.md
- src/analysis/locate.ml
- tests/test-dirs/document/external-pattern-comments.t
cc @trefis 
This are the two non-controversial commit extracted from #1562 
They improve get_doc when looking for comments in another compilation unit: the previous Typedtree iterator was wrong and get_doc relied on the old "comment list" heuristic in some cases involving value bindings patterns.
It also include the refactoring.
> Correctly traverse patterns when looking for docs in the typedtree

- CHANGES.md
- src/analysis/locate.ml
- tests/test-dirs/document/issue1540.t
Fix #1540 along with another issue where Merlin was unable to fetch documentation for the `mli` of the current compilation unit.
> Improv document request

- CHANGES.md
- src/frontend/ocamlmerlin/new/new_merlin.ml
- src/frontend/ocamlmerlin/ocamlmerlin.c
- tests/test-dirs/server-tests/chdir_to_root.t
- tests/test-dirs/server-tests/dune
On Windows, the process `ocamlmerlin-server.exe` is launched with the directory of the current source file as current working directory. This causes problems if one tries to move or delete that directory.
To avoid this problem, this PR makes sure to `chdir` to a different directory (TMPDIR) before launching `ocamlmerlin-server.exe`. Note that the same logic already exists for Unix: https://github.com/ocaml/merlin/blob/f1b877cd20d5c99b24bb8d051a63088488d26846/src/frontend/ocamlmerlin/ocamlmerlin.c#L314-L317
cc @dra27 @MisterDA 
Fixes #1474
> ocamlmerlin.c: chdir to root also on Windows to continue working if cwd is deleted

- CHANGES.md
- src/dot-merlin/dot_merlin_reader.ml
- src/dot-protocol/merlin_dot_protocol.ml
- src/dot-protocol/merlin_dot_protocol.mli
- src/kernel/mconfig_dot.ml
As discussed in: https://github.com/ocaml/ocaml-lsp/issues/1052
> Allow monadic IO in dot protocol

- CHANGES.md
- doc/dev/PROTOCOL.md
- src/frontend/ocamlmerlin/new/new_commands.ml
- src/frontend/ocamlmerlin/old/old_IO.ml
- src/frontend/ocamlmerlin/query_json.ml
- src/frontend/query_commands.ml
- src/frontend/query_protocol.ml
When this option is set to ``` `Project``` Merlin will (in the future) answer with project-wide occurrences.  In that case the answer also contains file paths associated to each locations.
This is useless without the rest of the project-wide occurrences machinery but since it is a breaking api change for ocaml-lsp it might be worth merging as soon as possible.
> Add a scope option to the occurrences command

- CHANGES.md
- emacs/merlin.el
The current `merlin-construct` interface is somewhat awkward.  It requires the user to switch buffers, and forces the use of the old-style built-in completion buffer, rather than using whatever completion interface the user has set up (e.g., ivy, helm).
Also make the following small improvements:
1. Fix some docstring typos
2. Clean up unused variable
3. Signal an error if the hole has no constructors, instead of just presenting an empty list of completions
> Elisp: make merlin-construct use the user's configured completion interface

- CHANGES.md
- src/kernel/mtyper.ml
- src/ocaml/typing/env.ml
- src/ocaml/typing/env.mli
- src/ocaml/typing/ident.ml
- src/ocaml/typing/ident.mli
- src/utils/stamped_hashtable.ml
- src/utils/stamped_hashtable.mli
This PR adds a mechanism to track the stamp of functor components cached in `fcomp_cache` and `fcomp_subst_cache`. They can they be removed from the cache when backtracking.
Its probably only necessary to track the components added to the persistent_env caches, this feature might be added later if this patch makes things too slow (or just worsen the problem :D).
> Cleanup functor caches

- CHANGES.md
- src/frontend/query_commands.ml
- tests/test-dirs/errors/no-cmi.t
In some cases `errors` command can alert about missing cmis that are, in fact, not missing.
This is due to `wrap_printing_env` setting `Cannot_load_cmis` in `Persistent_env`.
It looks like the forçage of `Typecore.force_delayed_checks` in `Typer.get_errors` requires `cmi` loading and thus should not happen under `wrap_printing_env`.
cc @ddickstein
> Fix false "no cmi" reporting from errors command

- tests/test-dirs/with-ppx/parsetree-cache.t/run.t
Text in test referenced -use-ppx-cache flag, which was changed to USE_PPX_CACHE directive.
> Fix text in test

- .github/workflows/changelog.yml
- README.md
This PR adds changelog check action, that fails CI when there is no entry to `CHANGES.md`.
For PRs that doesn't contain changes that should be logged, there should be a label `no changelog`. It needs to be added to merlin project by a maintainer, so that contributors can use it.
> Add changelog check to CI

- CHANGES.md
- emacs/merlin.el
Currently, "interrupted" is only logged when the result parsing is interrupted (by C-g), but it seems pretty clear that the original intent (and more useful behavior) was to log "interrupted" when the actual merlin call was interrupted.
We do this by setting up separate condition handlers for (1) the result parse failing; and (2) the merlin call or result parse being interrupted.
> Emacs: fix logging when merlin call is interrupted

- flake.lock
- flake.nix
As described [here](https://github.com/ocaml/merlin/tree/master#compilation), menhir should be pinned to specific version. This PR overrides menhir in flake.nix, so that it matches.
@rgrinberg , could you take a look please? :)
> Override menhir version in flake.nix

- CHANGES.md
- src/analysis/construct.ml
- src/analysis/construct.mli
- src/frontend/query_commands.ml
- tests/test-dirs/construct/c-prefix.t
As suggested in #1552, there shouldn't be any need to generate module prefixes for constructors or record fields when using `construct`, since the hole's type can be used with type-directed disambiguation.
Closes #1552.
> construct: Do not produce redundant prefixes

- flake.nix
Currently, merlin can only use `nix develop`.
This PR makes regular nix workflow work (`nix build`, `nix run`, `nix shell`).
Example command to test it with:
```
[rafal@nixos:~/Projects/Tarides/merlin]$ nix run . -- server
Usage: ocamlmerlin command [options] -- [compiler flags]
Help commands are:
-version        Print version and exit
-vnum           Print version number and exit
-warn-help      Show description of warning numbers
-flags-help     Show description of accepted compiler flags
-commands-help  Describe all accepted commands
```
> Improve nix flake

- CHANGES.md
- src/frontend/ocamlmerlin/ocamlmerlin.c
While playing with nix build of merlin, I came across this warning:
```
> In function 'snprintf',
>     inlined from 'connect_socket.constprop' at ocamlmerlin.c:262:5:
> /nix/store/i29k9pvl90385mpsavifqvm4rag684dn-glibc-2.37-8-dev/include/bits/stdio2.h:54:10: note: '__builtin___snprintf_chk' output between 3 and 4099 bytes into a destination of size 104
>    54 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    55 |                                    __glibc_objsize (__s), __fmt,
>       |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    56 |                                    __va_arg_pack ());
>       |                                    ~~~~~~~~~~~~~~~~~
``` …
> Constrain socket path buffer size

- CHANGES.md
- src/kernel/mpipeline.ml
- src/kernel/phase_cache.ml
- src/kernel/phase_cache.mli
- tests/test-dirs/with-ppx/issue1647-cache-invalidation.t
- tests/test-dirs/with-ppx/parsetree-cache.t/run.t
This PR add a reproduction and a fix for issue #1647
@pitag-ha could you have a look ?
> Reproduce and fix issue #1647 with cache invalidation

- CHANGES.md
- src/ocaml/typing/env.ml
- src/ocaml/typing/env.mli
- src/ocaml/typing/typedecl.ml
- tests/test-dirs/sp-normalization.t
This should resolves short-path normalization hanging in some situations.
> Upstream patch to short-path

- CHANGES.md
- src/utils/sexp.ml
The motivation for this came from failing to parse a response that Merlin returned due to the `-1` values for `col` in the `start` and `end` fields:
```
((assoc)
(class . "return")
(value (
(assoc)
(start (assoc) (line . 0) (col . -1))
(end (assoc) (line . 0) (col . -1))
(type . "typer")
(sub)
(valid . true)
(message . "omitted")))
(notifications)
(timing (assoc) (clock . 166) (cpu . 145) (query . 1) (pp . 0) (reader . 21) (ppx . 36) (typer . 76) (error . 11)))
```
> Add support for parsing negative numbers in sexps

- CHANGES.md
- README.md
- emacs/merlin.el
- merlin.opam
This PR adds support for `opam-switch-mode` (initially written by @hendriktews for [proof-general](https://proofgeneral.github.io) then as a separate ELPA package, further extended by @monnier and myself).
This new feature makes it possible to fully fix #1591, given it is now as easy as clicking on either of the "OPSW" menu-bar or the "OPSW" mode-bar, which changes Emacs underlying PATH accordingly (`exec-path`), and triggers the functions registered in the opam-switch-mode hook (typically, `merlin-stop-server`).
See the following screenshot of opam-switch-mode version 1.3 for a glimpse of the minor mode.
* This PR does NOT add opam-switch-mode as a dependency of merlin: it is an optional, accompanying package (only useful for ocaml developers that rely on opam), and it is mostly …
> feat(emacs): Add support for opam-switch-mode (>= 1.3)

- CHANGES.md
- src/analysis/construct.ml
- src/ocaml/typing/typecore.ml
- tests/test-dirs/construct/c-inline-record-issue1617.t
Type-checking failed because of the presence of a hole that was not handled correctly.
Fixes #1617 (cc @ddickstein )
> Illustrate and fix issue #1617 with construct and inlined records

- CHANGES.md
- src/kernel/mbrowse.ml
- tests/test-dirs/with-ppx/dune
- tests/test-dirs/with-ppx/issue1660-deriving-compare.t
> Prioritize non-ghost nodes when looking for best node. Fixes #1660

- CHANGES.md
- src/kernel/mconfig_dot.ml
- tests/test-dirs/config/no-dune.t
This PR correctly reset the state if the configuration reader (dune or dot-merlin-reader) failed to start and provide improved error messages than the current exception.
cc @ddickstein
> Improve error messages for missing config reader

- CHANGES.md
- src/analysis/locate.ml
- tests/test-dirs/locate/issue1667.t
> Fix confusion when scraping aliases of module / module-types

- CHANGES.md
- src/ocaml/merlin_specific/browse_raw.ml
- tests/test-dirs/issue1683-ill-formed-letop.t
`let+ pat1 = ... and+ pat2 = ...` are internally represented by tuples of patterns, themself encoded by a succesion of couples:
`[ ... [ pat1; pat2]; ...]` 
Merlin was too eager when flattening these tuples and messed with `pat1 if it happened to be a tuple itself.
Fixes #1683 
Fixes ocaml/ocaml-lsp#1182
> Fix letops tuples handling (fixes #1683 and ocaml/ocaml-lsp#1182)

- CHANGES.md
- vim/merlin/autoload/merlin.vim
MacVim comes with options +python3/dyn and -python3. This means currently merlin fails to load. This patch fixes that by testing for the dynamic python3.
I did not include the same for python/dyn because by now I think it's better not to support python 2.
> add test for dynamic python3 installation

- CHANGES.md
- src/kernel/mbrowse.ml
Fix #1689 by choosing the best ghost node when both are ghost.
It would take me many times longer to write a test than it took to write this PR. If anyone has ideas for a simple test, I'm open to it.
> Break ties between ghost nodes by looking at cursor position

- CHANGES.md
- doc/dev/CACHING.md
- emacs/merlin.el
- src/frontend/ocamlmerlin/new/new_merlin.ml
- src/frontend/ocamlmerlin/ocamlmerlin_server.ml
- src/kernel/mconfig.ml
- src/kernel/mconfig.mli
- tests/test-dirs/config/dot-merlin-reader/quoting.t
- tests/test-dirs/server-tests/cache-time.t
Second task from #1636
PoC:
The cache retention value was added to Mconfig. Call to `Mocaml.flush_caches` was moved to a place where Mconfig is available. Next step will be to create a flag that allows setting the config value from client. Last step is to use this flag from emacs/vim plugins.
> Configurable cache retention period

- CHANGES.md
- src/analysis/locate.ml
- tests/test-dirs/document/issue1513.t
- tests/test-dirs/locate/local-build-scheme.t
- tests/test-dirs/locate/non-local/ignore-kept-locs.t/run.t
Fixes #1699. Written with direction from @lpw25.
> uid_of_path can use the decl_id if shapes fail

- CHANGES.md
- src/kernel/mconfig.ml
- tests/test-dirs/with-cmi.t
Fixes #1703.
Merlin does not check the adequation between a module and its signature so there is no reason to handle that flag.
> Ignore `-cmi-file` flag

- CHANGES.md
- src/frontend/ocamlmerlin/new/new_merlin.ml
- tests/merlin-wrapper
This PR is a first step toward completing #1680
It enriches Merlin's responses with a new `heap_mbytes` field, that contains the total major heap size (in *megabytes*) after completing the request.
The implementation relies on using the `heap_words` field from  [Gc.stat](https://v2.ocaml.org/api/Gc.html).
This PR should be covering enough ground to satisfy the motivations 1 and 3 of the aforementined issue.
Motivation 2 maybe needs a finer grained solution with better granularity (ie. not only at the end of a request).
Let me know if there any refinement required, or if we need to add other fields, or if this is providing enough data as it is.
> Report current heap usage on Merlin response

- CHANGES.md
- src/frontend/ocamlmerlin/new/new_merlin.ml
- src/kernel/mpipeline.ml
- src/kernel/mpipeline.mli
- src/kernel/mtyper.ml
- src/kernel/mtyper.mli
- src/utils/file_cache.ml
- src/utils/file_cache.mli
- tests/merlin-wrapper
This PR adds cache statistics to merlin's telemetry, as in #1707 
Example output:
```json
"cache":{
"reader_phase":"miss",
"ppx_phase":"miss",
"typer":{
"reused":11,
"typed":0
},
"cmt":{
"hit":0,
"miss":0
},
"cmi":{
"hit":62,
"miss":0
}
}
```
> Cache hit/miss stats

- CHANGES.md
- src/ocaml/driver/pparse.ml
Fixes https://github.com/ocaml/merlin/issues/1724 thanks to @nojb spotting the problem in https://github.com/ocaml-ppx/ppxlib/pull/465.
> Use open_in_bin not open_in for merlinpp

- CHANGES.md
- src/analysis/jump.ml
- src/frontend/ocamlmerlin/new/new_commands.ml
- tests/test-dirs/motion/jump.t
This patch proposes to add the `module-type` parameter to the `jump` command.
Address partially #1656
> Allow jump to module type

- CHANGES.md
- src/analysis/destruct.ml
- tests/test-dirs/destruct/issue1661.t
Destructing a record punning field produced invalid OCaml syntax, as described in #1661, the case where we deconstruct on `a`, the `a` is substituted by the result of the deconstruction, whereas we would like to produce `a = destruct_result`. 
fix #1661
> destruct: destructing punned record field breaks syntax

- src/analysis/destruct.ml
This branch pull to `master` the refactoring introduced in https://github.com/voodoos/merlin/pull/10, taking into account field-puning processing (and other updates not introduced in preview 5.2.0). The test suite is still running, and each refactoring is in an isolated commit to facilitate integration with other branches.
> `destruct`: some refactoring

- CHANGES.md
- src/frontend/ocamlmerlin/ocamlmerlin_server.ml
Bringing in changes from [merlin-jst](https://github.com/janestreet/merlin-jst/pull/49).
From @catern:
The merlin server writes to pipes received from the merlin client process. If the read end of those pipes is closed, e.g. because the merlin client process was killed, then when the server writes to the pipe it will generate a SIGPIPE. This kills the Merlin server. Ignore the SIGPIPE instead of unnecessarily dying.
The fact that you get SIGPIPE when you write to a closed pipe is a classic Unix footgun, and this is the usual resolution. Another solution is to avoid pipes (in favor of e.g. socketpairs), but we can't do that because we write directly to the file descriptors received from the client.
> Ignore SIGPIPE in the Merlin server process

- CHANGES.md
- src/ocaml/preprocess/lexer_raw.mll
- tests/test-dirs/errors/issue1753.t
This test illustrate issue #1753
Commit [f07d346](https://github.com/ocaml/merlin/pull/1754/commits/f07d346e0620b0ecbeec1a9914814ab39a1dd781) should fix issue #1753
> Test and fix wrong error with string literal in comment

- CHANGES.md
- src/analysis/context.ml
- src/frontend/query_commands.ml
- src/ocaml/parsing/pprintast.mli
- tests/test-dirs/type-enclosing/need-parens.t
Context detection for longidents relies on some britle "where is the cursor in the lid" logic.
This PR add a special case to improve the handling of operators that requires parenthesis.
More precise locations in lid is required to actually get a clean and correct implementation, but at least this PR improves the situation a bit.
> Improve context detection for infix operators

- CHANGES.md
- src/analysis/ast_iterators.ml
- src/ocaml/typing/tast_iterator.ml
- src/ocaml/typing/tast_iterator.mli
- tests/test-dirs/with-ppx/issue1671-string.t
Current version of the indexing iterator actually works on the ppxed-typedtree. This means that we should detect part of the tree that are introduced by PPXes and not index them. 
This PR tries to do that in the usual way: it looks for the `merlin.hide` attribute on some strategic nodes.
@pitag-ha I am still a bit uncertain of which nodes should be considered to look for the `merlin.hide` attributes ?
Once again, that will only work with ppxes that actually use this attribute... I guess we can have that certainty only with ppxes written using `ppxlib` ?
We should try to devise a most robust way to distinguished ppxed part of the tree...
cc @Octachron since similar changes should be upstreamed at some point to prevent project-wide occurrences to return location that are actually coming …
> Do not index occurrences from ppxes 

- flake.lock
- flake.nix
- tests/test-dirs/inconsistent-assumptions.t
This changes flake.nix to build Merlin with OCaml 5.2 in order to support 5.2-only features.
Nixpkgs needed to be updated too.
> nix: Build with OCaml 5.2

- src/analysis/occurrences.ml
- src/analysis/occurrences.mli
- src/frontend/query_commands.ml
- tests/test-dirs/occurrences/mod-in-path-2.t
- tests/test-dirs/occurrences/mod-in-path-3.t
- tests/test-dirs/occurrences/mod-in-path.t
This reparsing has very bad performances. The correct way to deal with issue is to have the compiler store precise locations in longidents.
> Revert: remove reparsing of longident to index modules in paths

- CHANGES.md
- src/dot-merlin/dot_merlin_reader.ml
- src/dot-protocol/merlin_dot_protocol.ml
- src/dot-protocol/merlin_dot_protocol.mli
- src/kernel/mconfig.ml
- src/kernel/mconfig.mli
- src/kernel/mconfig_dot.ml
- src/kernel/mconfig_dot.mli
- tests/test-dirs/config/dot-merlin-reader/load-config.t
- tests/test-dirs/config/dot-merlin-reader/quoting.t
It an be used to tell Merlin the correct name of the current unit in the presence of wrapping.
> Add new `UNIT_NAME` configuration directive

- CHANGES.md
- vim/merlin/autoload/merlin.py
- vim/merlin/autoload/merlin.vim
This adds the `:MerlinOccurrencesProjectWide` command, that is very similar to `:MerlinOccurrences` command but passes the -scope project flag and uses the quickfix list instead of the location list.
Project-wide renames are not implemented and I don't think can be implemented easily. The substitution is done on Vim's side and opening an unbounded number of buffers could interact badly with plugins or different Vim configurations.
Perhaps project-wide renaming could be implemented by Merlin ?
Project-wide incremental search and rename are not implemented but could be in the future.
The same patch based on top of merlin with occurrences can be tested here: https://github.com/voodoos/merlin/pull/11
To test this, I do:
```
vim --cmd "set rtp^=vim/merlin" src/analysis/occurrences.ml
```
> Vim: Project-wide Occurrences

- CHANGES.md
- src/analysis/occurrences.ml
- tests/test-dirs/occurrences/project-wide/mli-vs-ml.t
Uids of the interface and implementation of a module might overlaps.
Until more information can be opbtain from the compiler we simply don't return external occurrences of types that are defined in the current interface file.
> Do not return PWO for defs in the current interface file

- CHANGES.md
- src/kernel/mtyper.ml
- src/ocaml/typing/env.ml
- src/ocaml/typing/env.mli
- src/ocaml/typing/shape.ml
- src/ocaml/typing/shape.mli
- src/utils/stamped_hashtable.ml
- src/utils/stamped_hashtable.mli
- tests/test-dirs/locate/dune
- tests/test-dirs/locate/in-implicit-trans-dep.t/run.t
- tests/test-dirs/occurrences/project-wide/dune
- tests/test-dirs/server-tests/dune
- tests/test-dirs/server-tests/pwo-uid-stability.t
- tests/test-dirs/server-tests/stable-uids.t
- tests/test-dirs/server-tests/warnings/backtrack.t
This ensures uids are stable between edits. This is important for features such as project-wide occurrences that first identify definitions' uids before looking them up in an external table. We need these uids to coincide with the ones of emitted by the compiler.
Since some tables use uids as keys, we have to clean them properly. This is done using the Stamped_hashtable datastructure introduced in 147f0c3.
> Reset the uid counter when restoring the typer's state

- CHANGES.md
- flake.lock
- src/analysis/context.ml
- src/analysis/occurrences.ml
- tests/test-dirs/locate/context-detection/cd-test.t/run.t
- tests/test-dirs/occurrences/from-origin.t
Improve the behavior on occurrences when on a label / constructor declaration
> At origin occurrences

- CHANGES.md
- vim/merlin/autoload/merlin.py
The python code for the vim plugin contains the strings `"\%"` and `"\|"` which generate SyntaxWarnings on python-3.12. Change the strings to `"\\%"` and `"\\|"` which produce the same output and silence the warning.
```
python 3.12.4 (main, Jun  6 2024, 18:26:44) [GCC 13.3.0] on linux
>>> print("\%\\%")
<stdin>:1: SyntaxWarning: invalid escape sequence '\%'
\%\%
>>> print("\|\\|")
<stdin>:1: SyntaxWarning: invalid escape sequence '\|'
\|\|
```
> merlin.py: fix python-3.12 Syntax warnings

- CHANGES.md
- vim/merlin/autoload/merlin.vim
- vim/merlin/doc/merlin.txt
MerlinPhrase calls an undefined function, vim_selectphrase, in the python code. This function was removed some years ago in change 8ebe7ff71ed367f814ca399cb1328f02f5c9d976. Remove all references to MerlinPhrase in the help docs, keybindings and vim functions which call it.
https://github.com/ocaml/merlin/commit/8ebe7ff71ed367f814ca399cb1328f02f5c9d976#diff-836f8a63886b2c63a113a107540d42a0b3a6272b016b2d45fb5bcffd99a708b4L754
it looks like it was re-implemented by https://github.com/ocaml/merlin/commit/89526e8e6ae19c07a628ca9fceb7f2f9cb98f894 with new (undocumented) vim bindings to `merlin#PhrasePrev` and `merlin#PhraseNext`
> vim: remove references to MerlinPhrase

- CHANGES.md
- src/analysis/destruct.ml
- tests/test-dirs/destruct/issue1770.t
~I don't know whether the fixed system might break some of the parameters generated by PPX. (Perhaps if there is a ghost on the parent expression, you can check that it is the `None` constructor?).~
After a conversation with @pitag-ha , we came to the conclusion that the introduction of ghost location in this context (which, in PPX terms, should be reserved for derivers) is a problem of semantics ‘on the PPX side’, so that **this fix**, which is based on ghost location, is not problematic (for PPX).
Fix #1770
> Refinement in the presence of optional arguments

- src/dot-merlin/dot_merlin_reader.ml
- tests/test-dirs/config/dot-merlin-reader/load-config.t
- tests/test-dirs/config/dot-merlin-reader/stdlib-config.t
Currently, the directive `STDLIB` inside a `.merlin` file is ignored. This PR fixes this bug.
> Fix ignorance of STDLIB in .merlin

- src/kernel/mconfig.ml
As title: just a small change to make a better error message for devs that want to see the name of an incorrectly-duplicated flag spec.
> Produce a better error message when a flag spec appears multiple times

- CHANGES.md
- src/analysis/inlay_hints.ml
- src/analysis/inlay_hints.mli
- src/commands/new_commands.ml
- src/commands/query_json.ml
- src/frontend/query_commands.ml
- src/frontend/query_protocol.ml
- src/ocaml/parsing/location_aux.ml
- src/ocaml/parsing/location_aux.mli
- src/utils/std.ml
- tests/test-dirs/inlay-hint/samples.t
- tests/test-dirs/inlay-hint/spec.t
Currently, the command returns a list of `postion * label` and the label is _computed_ in the sense of `lsp` : `: type_expr` but I guess we can just return the type without any formatting and let's the LSP server prefixing it? WDYT @voodoos?
> Inlay hint upstreaming

- CHANGES.md
- emacs/merlin.el
Since polarity research output a result in a popup that take the focus, the user experience was a little bit complicated. So the patch returns the result inside a dedicated buffer:
(I was not able to take a screenshot about the "before", because the popup was taking the focus...)
> Some UI improvement for `emacs/merlin-search`

- src/ocaml-index/bin/dune
- src/ocaml-index/bin/ocaml_index.ml
- src/ocaml-index/lib/index.ml
- src/ocaml-index/tests/tests-dirs/cmd.t
- src/ocaml-index/tests/tests-dirs/transitive-deps.t
This is a change we made in [merlin-jst](https://github.com/janestreet/merlin-jst/pull/88). Currently, ocaml-index takes a `-I` flag that enables adding paths to the load path to find cmt files to use for reducing shapes. This PR adds a `-H` flag that does the same thing, except it adds paths to the hidden load path.
When working with cms files (which merlin-jst does), the load paths must always be specified because cms files do not include the load path in them. This is not-so-useful when working with cmt files, which do include the loadpath, and so ocaml-index doesn't need to be explicitly passed the load path. However, this still seems like a nice feature to have incase it becomes important in the future.
> Add `-H` flag to `ocaml-index`

- CHANGES.md
- emacs/merlin-cap.el
- emacs/merlin.el
Let me know how you'd like me to approach this PR.  This is what we use internally at Jane Street, and it's been written to be relatively upstreamable.  At the same time, the old version of merlin-cap was in need of a lot of improvement and modernization to how the Emacs completion API is supposed to be used, and essentially none of the original code survived.  So it's kind of just a giant code drop, which I know is pretty hard to review.
The merlin-completion-at-point integration is completely rewritten.  The version before was simple and slow; the new version is much faster and much more featureful:
- Completions are requested for an entire module at once and filtered locally in Emacs rather than doing the filtering on the Merlin side.
- Completions are cached based on the OCaml atom …
> Rewrite merlin-completion-at-point integration to be faster and better

- .github/workflows/main.yml
- tests/test-dirs/config/dot-merlin-reader/dune
- tests/test-dirs/config/dune
- tests/test-dirs/hidden-deps/dune
- tests/test-dirs/locate/dune
- tests/test-dirs/occurrences/project-wide/dune
- tests/test-dirs/server-tests/dune
We cannot rely on OCaml-CI if we OCamlformat the codebase. This PR re-enables Github Action-based CI
> Re-enable Github actions CI

- src/dot-merlin/dot_merlin_reader.ml
- tests/test-dirs/config/dot-merlin-reader/load-config.t
At the moment, the `SOURCE_ROOT` directive is not properly read from .merlin files. This PR fixes the issue by ensuring the `dot_merlin_reader.ml` passes on the directive.
> Fix ignorace of SOURCE_ROOT directive

- CHANGES.md
- src/analysis/occurrences.ml
- tests/test-dirs/occurrences/project-wide/pwo-canonicalize.t
This fixes a minor bug in occurrences. See the test in the first commit (5fb1560f522617ef4d80f30166dda5ae84561a90), which demonstrates the issue.
> Canonicalize paths when finding occurrences

- src/sherlodoc/.ocamlformat-ignore
- src/sherlodoc/dune
- src/sherlodoc/type_parser.ml
- src/sherlodoc/type_parser.mli
Merlin package does not depend on menhir in release mode so we have to vendor the generated parser.
> Promote sherlodoc parser to sources

- src/kernel/mconfig.ml
- tests/test-dirs/config/dune
- tests/test-dirs/config/exclude-query-dir.t
When looking for `.cmt` files, Merlin doesn't currently respect the `EXCLUDE_QUERY_DIR` directive (see the first commit for a test case demonstrating the issue). This PR resolves this issue.
This PR corresponds to [PR 104 on Merlin-JST](https://github.com/janestreet/merlin-jst/pull/104)
> Fix `EXCLUDE_QUERY_DIR` for cmt files

- CHANGES.md
- src/analysis/occurrences.ml
- tests/test-dirs/occurrences/project-wide/pwo-canonicalize.t
- tests/test-dirs/occurrences/project-wide/pwo-relative.t
This PR resolves a bug where relative paths in an index are resolve against the `PWD` instead of based on the `SOURCE_ROOT` directive. See the first commit for a test case demonstrating the issue. I may have introduced this bug in #1840, or it may have predated that PR - I'm not sure.
> Occurrences canonicalization bugfix

- CHANGES.md
- src/analysis/jump.ml
- tests/test-dirs/jump-issue1862.t
Changes in the representation of functions in the `Typedtree` broke invariants in the jump-to-fun features.
> Fix issue with jump to "fun" after upgrade to 5.2

- src/analysis/misc_utils.ml
- src/analysis/misc_utils.mli
- src/analysis/type_enclosing.ml
- src/analysis/type_enclosing.mli
- src/frontend/query_commands.ml
- tests/test-dirs/hidden-deps/dash-h.t
- tests/test-dirs/issue1109.t/run.t
- tests/test-dirs/misc/load_path.t
- tests/test-dirs/type-enclosing/constructors_and_paths.t/run.t
- tests/test-dirs/type-enclosing/generic-types.t
- tests/test-dirs/type-enclosing/github1003.t/run.t
- tests/test-dirs/type-enclosing/issue1477.t
- tests/test-dirs/type-enclosing/letop.t/run.t
- tests/test-dirs/type-enclosing/mod-type.t/run.t
- tests/test-dirs/type-enclosing/objects.t/run.t
- tests/test-dirs/type-enclosing/record.t/run.t
- tests/test-dirs/type-enclosing/te-413-features.t
- tests/test-dirs/type-enclosing/te-modules.t
- tests/test-dirs/type-enclosing/types.t/run.t
Deduplication can only be done if the type have been printed which is an expensive process. We perform that printing only at the junction between the reconstructed identifier's enclosings and the ones from the tree nodes because we often want to keep both (often this gives the generic type and then its specialized version). All other duplicated ranges are removed.
> Fix type enclosing deduplication

- CHANGES.md
- vim/merlin/autoload/merlin.py
- vim/merlin/autoload/merlin.vim
- vim/merlin/doc/merlin.txt
This adds the `:MerlinSearchType` command to query for a value with a matching type. It works like the previous `:MerlinSearch` but uses the new search feature added in https://github.com/ocaml/merlin/pull/1828, the search results are shown in the completion menu.
`:MerlinSearch` switches between polarity search and search by type depending on the first character of the query, like is done in the emacs plugin.
Documentation about the three search functions is added.
> vim: Expose the search-by-type feature

- CHANGES.md
- src/analysis/locate.ml
- src/analysis/locate.mli
- src/analysis/occurrences.ml
- src/frontend/query_commands.ml
- src/ocaml-index/lib/index.ml
- src/ocaml-index/tests/tests-dirs/interfaces.t
- src/ocaml/typing/cmt_format.ml
- src/ocaml/typing/cmt_format.mli
- tests/test-dirs/locate/context-detection/cd-test.t/run.t
- tests/test-dirs/locate/dune
- tests/test-dirs/locate/issue1848.t
- tests/test-dirs/occurrences/project-wide/mli-vs-ml.t
In OCaml 5.3's cmts the uids contain information indicating there origin (an implementation or an interface). In this PR we use that information to jump to interface files when needed.
- This fixes issue #1848 
- This allows us to return occurrences in both the interface and implementation
This is sensible to the freshness of the cmt file for the current module. An heuristic based on identifiers is used to alleviate the risk of Merlin giving wrong answers when the cmts are out-of-date. If this proves insufficient we can make it stricter by checking the creation time of the artifacts.
> [503] Use source information in uids to jump to the correct file and provide occurrences in both the interface and the implementation

- .github/workflows/ocaml-lsp-compat.yml
- CHANGES.md
- src/analysis/tail_analysis.ml
- src/analysis/typed_hole.ml
- src/analysis/typed_hole.mli
- src/frontend/query_commands.ml
- src/ocaml/merlin_specific/browse_raw.ml
- src/ocaml/typing/cmt_format.ml
- src/ocaml/typing/printtyped.ml
- src/ocaml/typing/tast_iterator.ml
- src/ocaml/typing/tast_mapper.ml
- src/ocaml/typing/typecore.ml
- src/ocaml/typing/typedtree.ml
- src/ocaml/typing/typedtree.mli
- src/ocaml/typing/typemod.ml
- src/ocaml/typing/untypeast.ml
- src/ocaml/typing/value_rec_check.ml
In ocaml-flambda, we've added a new constructor to `Typedtree.expression_desc` named `Texp_hole`: https://github.com/ocaml-flambda/flambda-backend/pull/3310/files#diff-ed47e32f450beb29b2f22ff8073a5592865c82845687a224124858a6b6060fc3R504. This unfortunately conflicts with the `Texp_hole` constructor that Merlin adds to the same type in order to represent typed holes. To solve this, we are renaming what was Merlin's `Texp_hole` to `Texp_typed_hole`. For consistency, we are also renaming `Tmod_hole` to `Tmod_typed_hole`, even though there is no `Tmod_hole` in the compiler. This PR includes the same renames in order to minimize the diff with merlin-jst.
> Rename `Texp_hole` and `Tmod_hole`

- flake.lock
- flake.nix
Needed for fixing the CI of `merl-an`.
> Add alcotest in `flake.nix` (and regenerate lock)

- tests/test-dirs/occurrences/project-wide/union.t
A very important change. 
(`\n` cause escape issues on my machine)
> Remove anoying `\n` in test

- .github/workflows/ocaml-lsp-compat.yml
- CHANGES.md
- src/analysis/occurrences.ml
- src/analysis/occurrences.mli
- src/commands/query_json.ml
- src/frontend/query_commands.ml
- src/frontend/query_protocol.ml
- src/index-format/granular_set.ml
- src/index-format/granular_set.mli
- tests/test-dirs/occurrences/basic.t/run.t
- tests/test-dirs/occurrences/ext-variant.t
- tests/test-dirs/occurrences/issue1398.t/run.t
- tests/test-dirs/occurrences/issue1404.t
- tests/test-dirs/occurrences/issue1410.t
- tests/test-dirs/occurrences/issue827.t/run.t
- tests/test-dirs/occurrences/lid-locs.t
- tests/test-dirs/occurrences/mod-in-path-2.t
- tests/test-dirs/occurrences/mod-in-path-3.t
- tests/test-dirs/occurrences/mod-in-path.t
- tests/test-dirs/occurrences/no-def-mli-only.t
- tests/test-dirs/occurrences/occ-types.t
- tests/test-dirs/occurrences/pattern.t
- tests/test-dirs/occurrences/project-wide/for-renaming/r-modules-and-types.t
- tests/test-dirs/occurrences/project-wide/mli-vs-ml.t
- tests/test-dirs/occurrences/project-wide/prefix.t/run.t
- tests/test-dirs/occurrences/project-wide/pwo-basic.t
- tests/test-dirs/occurrences/project-wide/pwo-canonicalize.t
- tests/test-dirs/occurrences/project-wide/pwo-relative.t
- tests/test-dirs/occurrences/project-wide/stale-index.t
- tests/test-dirs/server-tests/pwo-uid-stability.t
This PR does two things:
1. Fix a bug with Merlin's detection of stale occurrences. Currently, depending on the layout of a repository, Merlin may not line up file paths correctly.
2. Currently, Merlin discards any occurrences it thinks might be stale. This PR changes this so that the stale occurrences are reported, but flagged as being stale.
The net effect for an end user should be nothing - the stale occurrences should still be reported by their editor. But this enables future LSP/editor work.
The reason these two items are in the same PR is:
- Doing just (1) would result in stale occurrences no longer being reported at all.
- Doing just (2) would be hard to test.
I encourage reviewing commit-by-commit. The tests pass after each commit, and changes (1) and (2) are separated into …
> Report stale occurrences

- .github/fuzzy-ci-helpers/irmin.3.10.0.opam.locked
Since Merl-an works by comparing diffs between two branches (base and merge), this branch must be merged before #1896 so that #1896 can be compared with `main` and correctly trigger all fuzzy-CI preconditions.
> Upgrade `irmin-lock` for `Fuzzy-CI`

- CHANGES.md
- src/analysis/outline.ml
- src/commands/query_json.ml
- src/frontend/query_protocol.ml
- tests/test-dirs/outline.t/foo.ml
- tests/test-dirs/outline.t/run.t
> Fix class type handling in outline

- tests/test-dirs/outline.t/foo.mli
- tests/test-dirs/outline.t/path.mli
- tests/test-dirs/outline.t/run.t
> Add tests for outline generation in .mli

- CHANGES.md
- src/analysis/outline.ml
- tests/test-dirs/outline.t/run.t
ocaml-lsp outline reports imbricated object inside let expression but merlin not. This fix aims to use merlin to generate outlines in ocaml-lsp without introduce regression in ocaml-lsp
The fix is ugly but I can refactor if needed.
cc @voodoos @xvw
> Handle object expression inside a let in outline

- CHANGES.md
- src/extend/extend_driver.ml
OpenBSD's [`execve(2)`](https://man.openbsd.org/execve#EINVAL) needs `argv` to contain at least one element.
> Fix `merlin_reader` functionality on OpenBSD

- CHANGES.md
- src/ocaml/typing/typecore.ml
- tests/test-dirs/recovery/issue1953.t
Fixes #1953.
The classic tell of the missing `raise_error`.
> Test & Fix recovery issue 1953

- CHANGES.md
- vim/merlin/autoload/merlin.py
The Vim plugin sometimes crashes due to an out-of-bound access when querying the preview text.
The error was:
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/nix/store/iifbn3ckdlz6wzjr899lmx6nh08lfccx-source/vim/merlin/autoload/merlin.py", line 563, in vim_occurrences
for pos in with_text_previews(lst):
^^^^^^^^^^^^^^^^^^^^^^^
File "/nix/store/iifbn3ckdlz6wzjr899lmx6nh08lfccx-source/vim/merlin/autoload/merlin.py", line 551, in with_text_previews
text = preview_lines_by_file[oc['file']][lnum]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 235
```
With this fix, the plugin find no text at all to show for each occurrences, indicating that there's a problem with `preview_lines_by_file` as well.
But I think `preview_lines_by_file` cannot be perfect (the …
> Vim: Fix crash when text preview is not accurate

- CHANGES.md
- doc/dev/PROTOCOL.md
- src/analysis/locate_types.ml
- src/analysis/locate_types.mli
- src/commands/new_commands.ml
- src/commands/query_json.ml
- src/frontend/query_commands.ml
- src/frontend/query_protocol.ml
- src/utils/std.ml
- tests/test-dirs/locate-types.t
This PR adds a new command, locate-type-multi, that we plan to use at Jane Street for some new VSCode functionality.
A useful current command in VSCode is "Go to Type Definition", which uses the `locate-type` query to go to the definition of the type of the identifier under the cursor. However, this command is rather limited - it only works on `Tconstrs`, and when the `Tconstr` carries arguments, it just ignores the args. In other words, the command doesn't provide the ability to go to a's defintion if the type is any of the following: `a t, (a * _), a -> _, _ -> a`.
`locate-type-multi`, instead of always just returning the location of a single identifier, returns a tree structure that represents all the identifiers within a type. So for example, if the type is `a -> (b * c)`, it returns …
> Add `locate_type_multi` query

- src/kernel/mconfig.ml
- src/kernel/mconfig.mli
- src/kernel/mtyper.ml
Use `-buffer-cache=no` to disable it.
cc @pitag-ha @xvw @lyrm
> Introduce `buffer-cache` flag to disable typedtree cache

- CHANGES.md
the entry `Add more short-paths tests cases (#1904)` was misplaced.
> Replace misplaced change section
